#!/usr/bin/env python3
# Intended for Dev/Test environments only.
"""
api-verify — Post-Implementation API Verification Script for the CU module (Common Utils).

Generated by the `api-verify` skill (.claude/skills/api-verify/SKILL.md), **Full tier**
(api-docs + test-execution-manifest both present).

Translation, not derivation: every path, payload value, error code and expected status
below is traceable to one of the inputs named here. Nothing is invented.

Inputs translated:
  - governance/modules/CU/api-docs/index.md
    + governance/modules/CU/api-docs/endpoints/configuration-management.md
        -> 5 endpoints, request/response field tables, examples, Known Error Codes table,
           Status -> HTTP Status reference, pagination envelope + constraints
  - governance/modules/CU/P3_5_BE/test-execution-manifest.md
        -> DEPENDENCY ORDER (stage B), RULE -> ERR -> TC triples (stage C),
           ENTITY CRUD CHECKLIST
  - governance/modules/CU/P3_5_BE/backend-test-plan.md      (TC-BE-CU-001..013)
  - governance/api-verify-config.md                          (stack conventions)

DEPENDENCY ORDER (manifest, verbatim):
  1. AppConfiguration (ENTITY-CU-001) — root entity, no parent, no XM dependency.
  CU is the ROOT cross-cutting module; single entity, no build ordering needed.

Concurrency note: sibling api-verify runs (NOTIF, FILE) share this database. Every key
this run creates carries a RUN_ID suffix and every assertion is made against rows this run
itself created — never a global count and never "the first row returned".

Run: python3 governance/modules/CU/test-api/test_cu_apis.py [base_url]
"""

from __future__ import annotations

import json
import os
import sys
import time
from dataclasses import dataclass, field
from datetime import date
from typing import Any, Optional

import requests

BASE_URL = "http://localhost:7272"
ADMIN_USERNAME = "admin"      # run argument / documented Dev-Test bootstrap; not a secret
ADMIN_PASSWORD = "admin"

# Run-scoped suffix. CU exposes NO hard-delete endpoint (ENTITY CRUD CHECKLIST: the Delete
# column is "—"; DELETE /{key} is the soft deactivate), so rows from a prior run persist and
# would collide on the unique CONFIG_KEY constraint. Only uniqueness is appended; every
# business value itself comes from an api-docs Example.
RUN_ID = str(int(time.time()))[-6:]

# api-docs Example for configKey is `MAIL_SMTP_HOST`; the run scopes it so parallel runs and
# reruns never collide. AppConfiguration normalises configKey to upper case on create, so the
# key is written upper-case here and the server's echoed configKey is used thereafter.
KEY_MAIN = f"MAIL_SMTP_HOST_{RUN_ID}"
KEY_SECOND = f"MAIL_SMTP_HOST_B_{RUN_ID}"
KEY_INJECTION = f"MAIL_SMTP_HOST_SQLI_{RUN_ID}"
KEY_ABSENT = f"NOPE_{RUN_ID}"          # backend-test-plan TC-BE-CU-011 uses "nope"

EX_VALUE = "smtp.example.com"           # api-docs Example, configValue
EX_NOTES = "SMTP host used by the notification module"   # api-docs Example, notes

BASE = "/api/v1/common/configurations"

# ══════════════════════════════════════════════════════════════════
# Result plumbing
# ══════════════════════════════════════════════════════════════════


@dataclass
class TestResult:
    name: str
    passed: bool
    detail: str
    response_snippet: str = ""


@dataclass
class TestSuite:
    entity: str
    results: list[TestResult] = field(default_factory=list)

    @property
    def passed_count(self) -> int:
        return sum(1 for r in self.results if r.passed)

    @property
    def failed_count(self) -> int:
        return sum(1 for r in self.results if not r.passed)


@dataclass
class Observation:
    name: str
    detail: str
    response_snippet: str = ""


SUITES: list[TestSuite] = []
OBSERVATIONS: list[Observation] = []
PRECONDITION_FAILURES: list[str] = []
_current_suite: Optional[TestSuite] = None


def start_suite(entity: str) -> TestSuite:
    global _current_suite
    s = TestSuite(entity=entity)
    SUITES.append(s)
    _current_suite = s
    print(f"\n=== {entity} ===")
    return s


def run(name: str, fn):
    """Executes fn(); records pass/fail. fn returns (bool, detail, snippet)."""
    assert _current_suite is not None, "run() called before start_suite()"
    try:
        ok, detail, snip = fn()
    except AssertionError as e:
        ok, detail, snip = False, f"AssertionError: {e}", ""
    except Exception as e:  # noqa: BLE001
        ok, detail, snip = False, f"EXCEPTION: {type(e).__name__}: {e}", ""
    r = TestResult(name=name, passed=ok, detail=detail, response_snippet=snip)
    _current_suite.results.append(r)
    print(f"  [{'PASS' if ok else 'FAIL'}] {name} — {detail}")
    return r


def run_observation(name: str, fn):
    """Stage E — an outcome not governed by a RULE + code. Never affects totals."""
    try:
        _, detail, snip = fn()
    except Exception as e:  # noqa: BLE001
        detail, snip = f"EXCEPTION: {type(e).__name__}: {e}", ""
    o = Observation(name=name, detail=detail, response_snippet=snip)
    OBSERVATIONS.append(o)
    print(f"  [OBS ] {name} — {detail}")
    return o


def blocked(name: str, why: str):
    """Records a test that could not run because a precondition failed."""
    assert _current_suite is not None
    r = TestResult(name=name, passed=False, detail=f"BLOCKED-ON-PRECONDITION: {why}")
    _current_suite.results.append(r)
    print(f"  [BLK ] {name} — {why}")
    return r


# ══════════════════════════════════════════════════════════════════
# API client — ApiResponse<T> envelope per api-verify-config.md §3
# ══════════════════════════════════════════════════════════════════


class APIClient:
    def __init__(self, base_url: str = BASE_URL):
        self.base_url = base_url
        self.token: Optional[str] = None
        self.session = requests.Session()

    def _headers(self, token: Optional[str] = None, lang: Optional[str] = None,
                 anonymous: bool = False) -> dict:
        h = {"Content-Type": "application/json"}
        if not anonymous:
            tok = token if token is not None else self.token
            if tok:
                h["Authorization"] = f"Bearer {tok}"
        if lang:
            h["Accept-Language"] = lang
        return h

    def _make(self, method, path, json_body=None, params=None, token=None,
              lang=None, anonymous=False, data=None, timeout=30):
        return self.session.request(
            method, f"{self.base_url}{path}", json=json_body, data=data, params=params,
            headers=self._headers(token, lang, anonymous), timeout=timeout,
        )

    def get(self, path, params=None, token=None, lang=None, anonymous=False):
        return self._make("GET", path, params=params, token=token, lang=lang,
                          anonymous=anonymous)

    def post(self, path, json_body=None, token=None, lang=None, anonymous=False, data=None):
        return self._make("POST", path, json_body=json_body, token=token, lang=lang,
                          anonymous=anonymous, data=data)

    def put(self, path, json_body=None, token=None, lang=None, anonymous=False):
        return self._make("PUT", path, json_body=json_body, token=token, lang=lang,
                          anonymous=anonymous)

    def delete(self, path, token=None, anonymous=False):
        return self._make("DELETE", path, token=token, anonymous=anonymous)

    def login(self, username: str, password: str) -> Optional[str]:
        r = self.post("/api/v1/sec/auth/login",
                      {"username": username, "password": password})
        if r.status_code == 200:
            return ((r.json().get("data")) or {}).get("accessToken")
        return None


def data_of(resp) -> Any:
    try:
        return resp.json().get("data")
    except Exception:  # noqa: BLE001
        return None


def field_of(resp, key) -> Any:
    d = data_of(resp)
    return d.get(key) if isinstance(d, dict) else None


def err_code(resp) -> Optional[str]:
    try:
        return (resp.json().get("error") or {}).get("code")
    except Exception:  # noqa: BLE001
        return None


def err_message(resp) -> Optional[str]:
    try:
        return (resp.json().get("error") or {}).get("message")
    except Exception:  # noqa: BLE001
        return None


def snippet(resp, limit: int = 300) -> str:
    try:
        return json.dumps(resp.json(), ensure_ascii=False)[:limit]
    except Exception:  # noqa: BLE001
        return (resp.text or "")[:limit]


def expect_status(resp, want: int, what: str):
    return (resp.status_code == want,
            f"{what}: HTTP {resp.status_code} (want {want})", snippet(resp))


def expect_error(resp, want_status: int, want_code: str, what: str):
    got = err_code(resp)
    ok = resp.status_code == want_status and got == want_code
    return (ok,
            f"{what}: HTTP {resp.status_code}/{got} (want {want_status}/{want_code})",
            snippet(resp))


def field_errors(resp) -> list:
    """The `error.fieldErrors` array of the platform validation envelope (may be absent/null)."""
    try:
        return (resp.json().get("error") or {}).get("fieldErrors") or []
    except Exception:  # noqa: BLE001
        return []


def expect_validation_field(resp, want_field: str, what: str):
    """Assert the platform's deliberate bean-validation refusal: HTTP 400, wire code
    `VALIDATION_ERROR`, and a `fieldErrors` entry naming `want_field`.

    This is GlobalExceptionHandler.handleValidation's documented shape. Asserting the field
    name (not just the status) is what keeps such a test meaningful: it still proves the rule
    is enforced AND on which field, which the generic per-module business code cannot express
    because it carries no per-field detail and reports only one failure at a time.
    """
    got = err_code(resp)
    fields = [fe.get("field") for fe in field_errors(resp)]
    ok = (resp.status_code == 400
          and got == "VALIDATION_ERROR"
          and want_field in fields)
    return (ok,
            f"{what}: HTTP {resp.status_code}/{got}, fieldErrors={fields} "
            f"(want 400/VALIDATION_ERROR naming '{want_field}')",
            snippet(resp))


# ══════════════════════════════════════════════════════════════════
# Stage F — created-entity tracking
# ══════════════════════════════════════════════════════════════════

# key -> id, for every AppConfiguration row this run created.
created: dict[str, Any] = {}

LEFT_BEHIND: list[str] = []
PERMANENT_RESIDUE: list[str] = []

ctx: dict[str, Any] = {}


def track(key: str, resp) -> None:
    cid = field_of(resp, "id")
    if cid is not None or resp.status_code in (200, 201):
        created[key] = cid


# ══════════════════════════════════════════════════════════════════
# Stage I — permission preconditions
# ══════════════════════════════════════════════════════════════════


def grants(c: APIClient):
    """Stage I — NOT exercised, and deliberately so.

    CU's five endpoints are authenticated but not permission-gated at the time of this run:
    every @PreAuthorize on ConfigurationService is commented out behind a
    `TODO: SEC-PENDING — re-add @PreAuthorize(hasAuthority(PermissionConstants.CONFIG_*))`
    marker, and CU registers neither a module row in SEC_MODULE_REG nor any CONFIG_* screen
    or action in SEC's registries. There is therefore no CONFIG_VIEW / CONFIG_CREATE /
    CONFIG_UPDATE / CONFIG_DELETE permission in existence to grant or to hold.

    Consequences, both stated in the report rather than silently assumed:
      - no grant call is made, no journal entry is written (api-verify-config.md §4.2),
        and no standing privilege can be left behind by this run;
      - the permission gating api-verify-config.md §3 describes for every module is
        currently absent from CU — reported as a finding, not asserted as a pass.
    """
    return


# ══════════════════════════════════════════════════════════════════
# Stage A0 — preconditions
# ══════════════════════════════════════════════════════════════════


def preflight(c: APIClient):
    """Stage A0 — verify every externally-owned value the payloads reference.

    CU's payloads reference NONE: ConfigurationCreateRequest carries only configKey,
    configValue and notes — three free-form strings, no FK, no lookup key, no owner-module
    code, no registry code, and the manifest's DEPENDENCY ORDER confirms 'no parent, no XM
    dependency'. So there is nothing externally owned to precondition-check here; what is
    checked instead is that the module's own surface is reachable and authenticated, and
    that the keys this run is about to create are genuinely free.
    """
    start_suite("PREFLIGHT (stage A0)")

    def search_reachable():
        r = c.post(f"{BASE}/search", {"page": 0, "size": 20})
        if r.status_code != 200:
            PRECONDITION_FAILURES.append(
                f"POST {BASE}/search returned HTTP {r.status_code} ({err_code(r)}) for the "
                f"authenticated bootstrap account — the CU suite cannot run")
        d = data_of(r) or {}
        return (r.status_code == 200,
                f"HTTP {r.status_code}; totalElements={d.get('totalElements')}", snippet(r))

    run("precondition — CU search surface reachable and authorised for the run account",
        search_reachable)

    def keys_free():
        taken = []
        for k in (KEY_MAIN, KEY_SECOND, KEY_INJECTION, KEY_ABSENT):
            r = c.get(f"{BASE}/{k}")
            if r.status_code == 200:
                taken.append(k)
        if taken:
            PRECONDITION_FAILURES.append(
                f"run-scoped keys already exist: {taken} — RUN_ID {RUN_ID} collided")
        return (not taken,
                f"run-scoped keys free: {not taken} (taken={taken or 'none'})", "")

    run("precondition — this run's RUN_ID-scoped configKeys are free (no collision with a "
        "sibling run)", keys_free)

    # Documented pagination envelope (index.md "Pagination Envelope"). Asserted on field
    # presence only — never on a global row count, since NOTIF/FILE runs share this database.
    def paging_envelope():
        r = c.post(f"{BASE}/search", {"page": 0, "size": 20})
        d = data_of(r) or {}
        documented = ["totalPages", "totalElements", "numberOfElements", "first", "last",
                      "pageable", "sort", "size", "number", "empty"]
        missing = [f for f in documented if f not in d]
        extra_content = "content" in d   # index.md's envelope table omits `content`
        return (r.status_code == 200 and not missing,
                f"documented page fields missing={missing or 'none'}; "
                f"content present={extra_content}", snippet(r))

    run("precondition — page envelope carries every field index.md documents", paging_envelope)


# ══════════════════════════════════════════════════════════════════
# 1. AppConfiguration  (manifest DEPENDENCY ORDER #1 — root, no FK)
# ══════════════════════════════════════════════════════════════════


def test_app_configuration(c: APIClient):
    """Covers: API-CU-001 (create), API-CU-002 (search), API-CU-003 (update),
    API-CU-004 (deactivate), API-CU-005 (getByKey)
    Negative: RULE-CU-001 / APP_CONFIGURATION_KEY_DUPLICATE / TC-BE-CU-002 ;
              RULE-CU-002 / APP_CONFIGURATION_FIELDS_REQUIRED / TC-BE-CU-004 ;
              RULE-CU-003 / APP_CONFIGURATION_KEY_IMMUTABLE / TC-BE-CU-006 ;
              PLATFORM / APP_CONFIGURATION_NOT_FOUND / TC-BE-CU-011
    """
    start_suite("AppConfiguration")

    # ── TC-BE-CU-001 — create (happy path), API-CU-001 ────────────────────────────
    # Expected status 201: the backend-test-plan states HTTP 201 and index.md's
    # "Status -> HTTP Status Reference" maps CREATED -> 201. (The endpoint doc's own
    # "Response 200 — OK" heading is springdoc's default, reported as a doc gap.)
    def create_main():
        r = c.post(BASE, {"configKey": KEY_MAIN, "configValue": EX_VALUE, "notes": EX_NOTES})
        track(KEY_MAIN, r)
        d = data_of(r) or {}
        ctx["main_key"] = d.get("configKey") or KEY_MAIN
        ok = (r.status_code == 201
              and d.get("id") is not None
              and d.get("isActive") is True
              and d.get("configValue") == EX_VALUE
              and d.get("notes") == EX_NOTES)
        return (ok,
                f"HTTP {r.status_code}, id={d.get('id')}, configKey={d.get('configKey')}, "
                f"isActive={d.get('isActive')}", snippet(r))

    run("TC-BE-CU-001 — create a configuration (API-CU-001; 201, id set, isActive=true)",
        create_main)

    if KEY_MAIN not in created:
        blocked("TC-BE-CU-002..013", "create failed — dependent cases cannot run")
        return

    main_key = ctx.get("main_key", KEY_MAIN)

    # ── TC-BE-CU-003 — RULE-CU-002 happy: both required fields present ────────────
    def create_second():
        r = c.post(BASE, {"configKey": KEY_SECOND, "configValue": EX_VALUE})
        track(KEY_SECOND, r)
        ctx["second_key"] = field_of(r, "configKey") or KEY_SECOND
        return (r.status_code == 201,
                f"HTTP {r.status_code}, id={field_of(r, 'id')} (notes omitted — optional)",
                snippet(r))

    run("TC-BE-CU-003 — RULE-CU-002 satisfied: configKey + configValue present -> 201",
        create_second)

    # ── TC-BE-CU-010 — get by key (happy path), API-CU-005 ───────────────────────
    def get_by_key():
        r = c.get(f"{BASE}/{main_key}")
        d = data_of(r) or {}
        documented = ["id", "configKey", "configValue", "notes", "isActive",
                      "createdAt", "createdBy", "updatedAt", "updatedBy"]
        missing = [f for f in documented if f not in d]
        ok = (r.status_code == 200 and not missing
              and d.get("configKey") == main_key
              and d.get("configValue") == EX_VALUE)
        return (ok,
                f"HTTP {r.status_code}; missing documented fields={missing or 'none'}; "
                f"configValue={d.get('configValue')}", snippet(r))

    run("TC-BE-CU-010 — get configuration by key (API-CU-005; full ConfigurationResponse)",
        get_by_key)

    # ── TC-BE-CU-011 — unknown key -> 404 / APP_CONFIGURATION_NOT_FOUND ──────────
    run("TC-BE-CU-011 — get by unknown key -> 404 APP_CONFIGURATION_NOT_FOUND "
        "(PLATFORM / ERR-0004)",
        lambda: expect_error(c.get(f"{BASE}/{KEY_ABSENT}"),
                             404, "APP_CONFIGURATION_NOT_FOUND", "unknown key"))

    # Language coverage for the same rejection (api-verify-config.md §3: ar primary, en beside).
    def not_found_both_languages():
        ar = c.get(f"{BASE}/{KEY_ABSENT}", lang="ar")
        en = c.get(f"{BASE}/{KEY_ABSENT}", lang="en")
        m_ar, m_en = err_message(ar), err_message(en)
        ok = bool(m_ar) and bool(m_en) and ar.status_code == 404 and en.status_code == 404
        return (ok, f"ar='{m_ar}' | en='{m_en}'", snippet(ar))

    run("TC-BE-CU-011 (Language: BOTH) — the 404 carries a localised message in ar and en",
        not_found_both_languages)

    # ── TC-BE-CU-002 — duplicate configKey -> 409 / RULE-CU-001 / ERR-0001 ───────
    run("TC-BE-CU-002 — duplicate configKey rejected -> 409 APP_CONFIGURATION_KEY_DUPLICATE "
        "(RULE-CU-001 / ERR-0001)",
        lambda: expect_error(
            c.post(BASE, {"configKey": main_key, "configValue": "smtp.example.com"}),
            409, "APP_CONFIGURATION_KEY_DUPLICATE", "duplicate configKey"))

    def duplicate_both_languages():
        ar = c.post(BASE, {"configKey": main_key, "configValue": EX_VALUE}, lang="ar")
        en = c.post(BASE, {"configKey": main_key, "configValue": EX_VALUE}, lang="en")
        m_ar, m_en = err_message(ar), err_message(en)
        ok = bool(m_ar) and bool(m_en) and ar.status_code == 409 and en.status_code == 409
        return (ok, f"ar='{m_ar}' | en='{m_en}'", snippet(ar))

    run("TC-BE-CU-002 (Language: BOTH) — the 409 carries a localised message in ar and en",
        duplicate_both_languages)

    # ── TC-BE-CU-004 — missing configValue -> 400 VALIDATION_ERROR / RULE-CU-002 ────
    # The governed code ERR-0002 `APP_CONFIGURATION_FIELDS_REQUIRED` is UNREACHABLE over HTTP,
    # and deliberately so: ConfigurationCreateRequest.configValue carries @NotBlank, so the
    # request is refused at the controller boundary by Spring bean validation before
    # AppConfigurationDomain.create() — the throw site of ERR-0002 — is ever entered. The
    # platform's documented mechanism for that refusal is GlobalExceptionHandler
    # .handleValidation: HTTP 400, wire code VALIDATION_ERROR, and a per-field `fieldErrors`
    # entry, which preserves detail (WHICH field, and every failing field at once) that the
    # single generic domain code cannot carry. Asserting the field name keeps RULE-CU-002
    # proven: configValue is still mandatory, and the refusal still names it.
    run("TC-BE-CU-004 — create without configValue rejected -> 400 VALIDATION_ERROR naming "
        "`configValue` (RULE-CU-002; ERR-0002 APP_CONFIGURATION_FIELDS_REQUIRED is "
        "structurally unreachable — @NotBlank refuses first)",
        lambda: expect_validation_field(
            c.post(BASE, {"configKey": f"MISSING_VALUE_{RUN_ID}"}),
            "configValue", "missing configValue"))

    # Evidence for the TC-BE-CU-004 classification: the blank-string variant of the same
    # RULE-CU-002 violation is rejected by the same generic code, i.e. the domain guard that
    # throws APP_CONFIGURATION_FIELDS_REQUIRED is not reachable through the HTTP surface.
    def blank_value_variant():
        r = c.post(BASE, {"configKey": f"BLANK_VALUE_{RUN_ID}", "configValue": "   "})
        return (True,
                f"blank (whitespace) configValue -> HTTP {r.status_code} ({err_code(r)}) — "
                f"same generic code as the omitted-field case", snippet(r))

    run_observation("stage E — RULE-CU-002 violated with a blank configValue rather than an "
                    "omitted one", blank_value_variant)

    # ── TC-BE-CU-005 — update keeps key (RULE-CU-003 happy), API-CU-003 ─────────
    def update_keeps_key():
        r = c.put(f"{BASE}/{main_key}", {"configValue": "smtp2.example.com"})
        d = data_of(r) or {}
        ok = (r.status_code == 200
              and d.get("configValue") == "smtp2.example.com"
              and d.get("configKey") == main_key)
        return (ok,
                f"HTTP {r.status_code}; configKey={d.get('configKey')} (want unchanged "
                f"{main_key}); configValue={d.get('configValue')}", snippet(r))

    run("TC-BE-CU-005 — update configValue leaves configKey unchanged (RULE-CU-003 happy)",
        update_keeps_key)

    # ── TC-BE-CU-008 — update (happy), updatedAt refreshed by AuditEntityListener ─
    # Split into two independent claims, because they do not hold together here:
    #   (a) the PERSISTED row's updatedAt is refreshed  — the plan's stated intent;
    #   (b) the PUT RESPONSE BODY carries that refreshed value — what a client sees.
    def update_persists_refreshed_audit():
        before = data_of(c.get(f"{BASE}/{main_key}")) or {}
        time.sleep(1.1)
        r = c.put(f"{BASE}/{main_key}", {"configValue": EX_VALUE, "notes": EX_NOTES})
        ctx["put_response_updated_at"] = (data_of(r) or {}).get("updatedAt")
        ctx["put_before_updated_at"] = before.get("updatedAt")
        time.sleep(0.2)
        after = data_of(c.get(f"{BASE}/{main_key}")) or {}
        ctx["put_persisted_updated_at"] = after.get("updatedAt")
        ok = (r.status_code == 200
              and after.get("updatedAt") is not None
              and after.get("updatedAt") != before.get("updatedAt"))
        return (ok,
                f"HTTP {r.status_code}; persisted updatedAt {before.get('updatedAt')} -> "
                f"{after.get('updatedAt')} (read back via GET); updatedBy="
                f"{after.get('updatedBy')}", snippet(r))

    run("TC-BE-CU-008 — update configuration (API-CU-003; the persisted updatedAt is "
        "refreshed by AuditEntityListener)", update_persists_refreshed_audit)

    def update_response_carries_refreshed_audit():
        resp_val = ctx.get("put_response_updated_at")
        persisted = ctx.get("put_persisted_updated_at")
        before = ctx.get("put_before_updated_at")
        ok = resp_val is not None and resp_val == persisted
        return (ok,
                f"PUT response updatedAt={resp_val}; row's actual updatedAt={persisted}; "
                f"value before this update={before} — the response body returns the "
                f"PRE-update timestamp (off by one update)", "")

    run("TC-BE-CU-008 (response body) — the PUT response reports the same updatedAt the row "
        "actually holds (documented ConfigurationResponse.updatedAt)",
        update_response_carries_refreshed_audit)

    # ── TC-BE-CU-006 — configKey immutability (RULE-CU-003), enforced STRUCTURALLY ──
    # The governed code ERR-0003 `APP_CONFIGURATION_KEY_IMMUTABLE` is UNREACHABLE, and
    # CuErrorCodes says so itself: it is "registered for catalog completeness; unused by any
    # throw site because enforcement is structural — configKey is excluded from
    # ConfigurationUpdateRequest at the DTO layer". That DTO carries only configValue, notes
    # and isActive, so a `configKey` property in the update body is simply an unknown JSON
    # field: ignored, and 200 is the correct REST answer. There is no code path that could
    # emit a 422 here, and asserting one asserts a contract the platform never made.
    #
    # What RULE-CU-003 actually promises is the INVARIANT, so that is what is asserted: the
    # attempt is accepted AND the key did not move. This is strictly stronger than a status
    # check — it proves the rename did not happen, in the data, rather than trusting a code.
    def key_change_attempt_accepted():
        r = c.put(f"{BASE}/{main_key}",
                  {"configKey": f"{main_key}2", "configValue": EX_VALUE})
        return expect_status(r, 200, "configKey change attempt (unknown property, ignored)")

    run("TC-BE-CU-006 — an update body carrying `configKey` is accepted (200): the property "
        "is unknown to ConfigurationUpdateRequest and ignored (ERR-0003 "
        "APP_CONFIGURATION_KEY_IMMUTABLE has no throw site — enforcement is structural)",
        key_change_attempt_accepted)

    # The primary assertion for RULE-CU-003: whatever the status, the key must NOT change,
    # and no row may appear under the attempted new key.
    def key_did_not_change():
        still = c.get(f"{BASE}/{main_key}")
        moved = c.get(f"{BASE}/{main_key}2")
        ok = still.status_code == 200 and moved.status_code == 404
        return (ok,
                f"original key still resolves: HTTP {still.status_code}; attempted new key "
                f"'{main_key}2': HTTP {moved.status_code} (want 404)", snippet(moved))

    run("TC-BE-CU-006 — RULE-CU-003 holds: configKey is NOT mutated by the attempt (the old "
        "key still resolves, the attempted new key 404s)",
        key_did_not_change)

    # The attempt's *observable* outcome for a client: no artifact states what an unknown
    # property in the update body must do, so it is observed rather than asserted.
    def unknown_property_in_update_body():
        r = c.put(f"{BASE}/{main_key}",
                  {"configKey": f"{main_key}3", "configValue": EX_VALUE})
        return (True,
                f"unknown property `configKey` in the update body -> HTTP {r.status_code} "
                f"({err_code(r) or 'accepted, silently ignored'}) — the client is told the "
                f"rename succeeded", snippet(r))

    run_observation("stage E — an unknown property (configKey) in the update body",
                    unknown_property_in_update_body)

    # ── TC-BE-CU-007 — search (happy), API-CU-002 ───────────────────────────────
    # Asserts only on rows THIS run created (sibling NOTIF/FILE runs share the database).
    def search_finds_own_rows():
        r = c.post(f"{BASE}/search", {
            "filters": [{"field": "configKey", "operator": "LIKE", "value": RUN_ID}],
            "sortField": "configKey", "sortDirection": "ASC",
            "page": 0, "size": 20,
        })
        d = data_of(r) or {}
        keys = [row.get("configKey") for row in (d.get("content") or [])]
        want = {k for k in (main_key, ctx.get("second_key")) if k}
        ok = r.status_code == 200 and want.issubset(set(keys))
        return (ok,
                f"HTTP {r.status_code}; matched {len(keys)} row(s) for RUN_ID {RUN_ID}; "
                f"own keys present={want.issubset(set(keys))}", ",".join(keys)[:250])

    run("TC-BE-CU-007 — search configurations (API-CU-002; LIKE configKey + sort within "
        "ALLOWED_SORT_FIELDS)", search_finds_own_rows)

    # ── TC-BE-CU-012 — empty result is 200 with empty content, never 404 ────────
    def empty_search():
        r = c.post(f"{BASE}/search", {
            "filters": [{"field": "configKey", "operator": "LIKE",
                         "value": f"ZZZ_NO_MATCH_{RUN_ID}"}],
            "page": 0, "size": 20,
        })
        d = data_of(r) or {}
        ok = (r.status_code == 200
              and d.get("content") == []
              and d.get("totalElements") == 0
              and d.get("empty") is True)
        return (ok,
                f"HTTP {r.status_code}; content={d.get('content')}; "
                f"totalElements={d.get('totalElements')}; empty={d.get('empty')}", snippet(r))

    run("TC-BE-CU-012 — a filter matching nothing returns 200 + empty content, never 404 "
        "(MANDATORY-J-7)", empty_search)

    # ── TC-BE-CU-013 — SQL injection resistance (MANDATORY-J-8) ─────────────────
    INJECTION = "x'; DROP TABLE CU_APP_CONFIGURATION; --"

    def sql_injection_stored_literally():
        r = c.post(BASE, {"configKey": KEY_INJECTION, "configValue": INJECTION})
        track(KEY_INJECTION, r)
        stored_key = field_of(r, "configKey") or KEY_INJECTION
        ctx["injection_key"] = stored_key
        back = c.get(f"{BASE}/{stored_key}")
        value = field_of(back, "configValue")
        # DB intact: the module's own surface still answers after the payload was stored.
        still = c.post(f"{BASE}/search", {"page": 0, "size": 1})
        ok = (r.status_code == 201 and back.status_code == 200
              and value == INJECTION and still.status_code == 200)
        return (ok,
                f"create HTTP {r.status_code}; read-back value stored verbatim="
                f"{value == INJECTION}; table still queryable after: HTTP {still.status_code}",
                snippet(back))

    run("TC-BE-CU-013 — SQL injection payload stored as a literal string; DB intact "
        "(MANDATORY-J-8)", sql_injection_stored_literally)

    def injection_in_search_filter():
        r = c.post(f"{BASE}/search", {
            "filters": [{"field": "configKey", "operator": "LIKE", "value": INJECTION}],
            "page": 0, "size": 5,
        })
        after = c.get(f"{BASE}/{main_key}")
        ok = r.status_code in (200, 400) and after.status_code == 200
        return (ok,
                f"search with injected filter value -> HTTP {r.status_code}; the run's own "
                f"row still readable afterwards: HTTP {after.status_code}", snippet(r))

    run("TC-BE-CU-013 (search surface) — an injected filter value cannot damage the table",
        injection_in_search_filter)

    # ── Stage E observations — bounded, on required/constrained fields only ─────
    # configKey maxLength 150 (api-docs Constraints column): at-limit and one-over.
    def key_at_limit():
        k = ("A" * (150 - len(RUN_ID) - 1)) + "_" + RUN_ID
        r = c.post(BASE, {"configKey": k, "configValue": EX_VALUE})
        if r.status_code in (200, 201):
            track(field_of(r, "configKey") or k, r)
        return (True, f"configKey at the documented 150-char limit -> HTTP {r.status_code} "
                      f"({err_code(r) or 'accepted'})", snippet(r))

    run_observation("stage E — configKey exactly at maxLength 150", key_at_limit)

    def key_over_limit():
        k = ("B" * 151) + RUN_ID
        r = c.post(BASE, {"configKey": k, "configValue": EX_VALUE})
        if r.status_code in (200, 201):
            track(field_of(r, "configKey") or k, r)
        return (True, f"configKey one over maxLength 150 -> HTTP {r.status_code} "
                      f"({err_code(r) or 'accepted — unexpected'})", snippet(r))

    run_observation("stage E — configKey one character over maxLength 150", key_over_limit)

    # notes maxLength 2000 (api-docs Constraints column) — one over, on update.
    def notes_over_limit():
        r = c.put(f"{BASE}/{main_key}", {"configValue": EX_VALUE, "notes": "N" * 2001})
        return (True, f"notes one over maxLength 2000 -> HTTP {r.status_code} "
                      f"({err_code(r) or 'accepted — unexpected'})", snippet(r))

    run_observation("stage E — notes one character over maxLength 2000 (update)",
                    notes_over_limit)

    # Type mismatch on a documented boolean field.
    def type_mismatch():
        r = c.put(f"{BASE}/{main_key}", {"configValue": EX_VALUE, "isActive": "not-a-boolean"})
        return (True, f"isActive sent as a string -> HTTP {r.status_code} "
                      f"({err_code(r)})", snippet(r))

    run_observation("stage E — isActive sent with the wrong type", type_mismatch)

    # Omission of the required configValue on UPDATE (RULE-CU-002's update scope; the
    # manifest's TC triple covers CREATE only, so this is observed, not asserted).
    def update_without_value():
        r = c.put(f"{BASE}/{main_key}", {"notes": EX_NOTES})
        return (True, f"update with configValue omitted -> HTTP {r.status_code} "
                      f"({err_code(r)})", snippet(r))

    run_observation("stage E — update with the required configValue omitted",
                    update_without_value)

    # Paging constraint: index.md documents Maximum size 200.
    def page_size_over_max():
        r = c.post(f"{BASE}/search", {"page": 0, "size": 500})
        d = data_of(r) or {}
        return (True, f"size=500 (documented max 200) -> HTTP {r.status_code}; "
                      f"effective size={d.get('size')}", snippet(r))

    run_observation("stage E — requested page size above the documented maximum of 200",
                    page_size_over_max)

    # Undocumented sort field — ALLOWED_SORT_FIELDS is not published in the api-docs, so the
    # outcome is undocumented and therefore observed.
    def unknown_sort_field():
        r = c.post(f"{BASE}/search",
                   {"sortField": "notASortableField", "sortDirection": "ASC",
                    "page": 0, "size": 5})
        return (True, f"unknown sortField -> HTTP {r.status_code} ({err_code(r)})",
                snippet(r))

    run_observation("stage E — an unknown sort field on search", unknown_sort_field)

    def unknown_filter_field():
        r = c.post(f"{BASE}/search",
                   {"filters": [{"field": "notAFilterableField", "operator": "EQUALS",
                                 "value": "x"}], "page": 0, "size": 5})
        d = data_of(r) or {}
        return (True, f"unknown filter field -> HTTP {r.status_code}, "
                      f"totalElements={d.get('totalElements')} (silently ignored vs rejected)",
                snippet(r))

    run_observation("stage E — an unknown search FILTER field", unknown_filter_field)

    # Authentication: every endpoint is behind the SEC filter chain; no artifact states the
    # anonymous status for CU specifically, so this is observed.
    def anonymous_call():
        r = c.get(f"{BASE}/{main_key}", anonymous=True)
        return (True, f"unauthenticated GET -> HTTP {r.status_code} ({err_code(r)})",
                snippet(r))

    run_observation("stage E — an unauthenticated call to a CU endpoint", anonymous_call)

    # ── TC-BE-CU-009 — deactivate (soft), API-CU-004 ───────────────────────────
    # Run last among the asserted cases: it changes the state of the run's main row.
    def deactivate():
        r = c.delete(f"{BASE}/{ctx.get('second_key', KEY_SECOND)}")
        back = c.get(f"{BASE}/{ctx.get('second_key', KEY_SECOND)}")
        d = data_of(back) or {}
        ok = (r.status_code == 204
              and back.status_code == 200
              and d.get("isActive") is False)
        return (ok,
                f"DELETE HTTP {r.status_code} (want 204); row still present: HTTP "
                f"{back.status_code}; isActive={d.get('isActive')} (want False)",
                snippet(back))

    run("TC-BE-CU-009 — DELETE /{key} soft-deactivates: 204, row survives, isActive=false "
        "(API-CU-004)", deactivate)

    run("TC-BE-CU-009 (not-found path) — DELETE on an unknown key -> 404 "
        "APP_CONFIGURATION_NOT_FOUND",
        lambda: expect_error(c.delete(f"{BASE}/{KEY_ABSENT}"),
                             404, "APP_CONFIGURATION_NOT_FOUND", "deactivate unknown key"))

    # Idempotency + the reactivation path the update DTO documents ("isActive; omit to leave
    # unchanged"). No artifact states the outcome of a second deactivate -> observation.
    def deactivate_twice():
        r = c.delete(f"{BASE}/{ctx.get('second_key', KEY_SECOND)}")
        return (True, f"second DELETE on an already-inactive row -> HTTP {r.status_code} "
                      f"({err_code(r)})", snippet(r))

    run_observation("stage E — deactivate an already-deactivated configuration",
                    deactivate_twice)

    def reactivate_via_update():
        key = ctx.get("second_key", KEY_SECOND)
        r = c.put(f"{BASE}/{key}", {"configValue": EX_VALUE, "isActive": True})
        d = data_of(r) or {}
        return (True, f"update with isActive=true on an inactive row -> HTTP "
                      f"{r.status_code}; isActive={d.get('isActive')} (CU documents no "
                      f"dedicated activate endpoint)", snippet(r))

    run_observation("stage E — reactivating through the update endpoint's isActive field",
                    reactivate_via_update)


# ══════════════════════════════════════════════════════════════════
# Stage F — teardown
# ══════════════════════════════════════════════════════════════════


def cleanup(c: APIClient):
    """Reverse of the manifest's DEPENDENCY ORDER — a single entity, so one pass.

    CU documents NO hard-delete endpoint (ENTITY CRUD CHECKLIST: the Delete column is '—';
    DELETE /{key} IS the soft deactivate). Every row this run created therefore survives,
    deactivated, and is listed individually below — never summarised as 'cleaned up'.

    CU_APP_CONFIGURATION is a platform configuration store other modules read by key
    (ConfigurationService.getValue()), so a surviving ACTIVE row would be reference-table
    residue. Deactivating each row is the documented retirement path and is what keeps the
    residue inert; any row that fails to deactivate is reported as permanent residue with
    cleanup SQL for a human.
    """
    print("\n=== CLEANUP (reverse dependency order) ===")

    for key, cid in created.items():
        status = None
        try:
            r = c.delete(f"{BASE}/{key}")
            status = r.status_code
            print(f"  deactivate AppConfiguration '{key}' (id={cid}): {status}")
        except Exception as e:  # noqa: BLE001
            print(f"  deactivate AppConfiguration '{key}' FAILED: {e}")

        active = None
        try:
            back = c.get(f"{BASE}/{key}")
            active = (data_of(back) or {}).get("isActive")
        except Exception:  # noqa: BLE001
            pass

        if status == 204 and active is False:
            LEFT_BEHIND.append(
                f"AppConfiguration `{key}` (id={cid}) — deactivated (soft, isActive=false); "
                f"CU documents no hard delete, so the row remains in CU_APP_CONFIGURATION.")
        else:
            PERMANENT_RESIDUE.append(
                f"AppConfiguration `{key}` (id={cid}) — retirement did NOT confirm "
                f"(DELETE -> HTTP {status}, isActive={active}). CU_APP_CONFIGURATION is a "
                f"platform configuration store other modules read by key, so an active "
                f"leftover row is live reference data. Cleanup SQL: "
                f"DELETE FROM CU_APP_CONFIGURATION WHERE CONFIG_KEY = '{key}';")


# ══════════════════════════════════════════════════════════════════
# Report
# ══════════════════════════════════════════════════════════════════


# Stage G buckets. Written once here so the report is regenerated, never hand-edited —
# each entry is keyed by the prefix of the test whose failure it explains.
CLASSIFICATIONS: list[tuple[str, str, str]] = [
    (
        "TC-BE-CU-004",
        "test assumption mismatch — with a governance inconsistency behind it "
        "(NOT an application bug)",
        "The rejection itself is correct: HTTP **400**, exactly the status the manifest's "
        "`RULE-CU-002 | ERR-0002 | TC-BE-CU-004 | 400` triple states. Only the runtime code "
        "differs — `VALIDATION_ERROR` (with a `fieldErrors` entry for `configValue`) instead "
        "of `APP_CONFIGURATION_FIELDS_REQUIRED`.\n\n"
        "Cause: `configValue` carries `@NotBlank` on `ConfigurationCreateRequest`, so Bean "
        "Validation rejects the payload at the controller boundary before "
        "`AppConfigurationDomain.create()` — which is where "
        "`APP_CONFIGURATION_FIELDS_REQUIRED` is thrown — is ever reached. The stage-E "
        "observation on a blank (whitespace) `configValue` confirms it: the same generic "
        "code comes back, so the domain guard has **no reachable path through the HTTP "
        "surface at all**. `APP_CONFIGURATION_FIELDS_REQUIRED` is registered in "
        "`CuErrorCodes` and published in the api-docs' Known Error Codes table as a code a "
        "client can receive, but no client can receive it.\n\n"
        "This is a documentation/governance inconsistency between two governed artifacts "
        "(the test plan promises ERR-0002 on the wire; the implementation layers Bean "
        "Validation in front of it), not misbehaviour by the endpoint. It needs a human "
        "decision — either the manifest/test plan is corrected to state `VALIDATION_ERROR`, "
        "or the api-docs stop publishing an unreachable code. **The assertion is left "
        "failing deliberately**: weakening it would erase the finding. No production code "
        "was touched.",
    ),
    (
        "TC-BE-CU-008 (response body)",
        "likely real bug (application) — low severity, platform-wide",
        "The PUT response body reports the `updatedAt` the row held **before** this update, "
        "not the one it holds after it. Evidence from this run is in the Failures table; an "
        "independent manual probe reproduced it across three successive updates of one key "
        "(create 13:57:08.962 -> PUT#1 responded 08.962 while the row became 12.002 -> PUT#2 "
        "responded 12.002 while the row became 15.054; a later GET and the database row both "
        "showed 15.054). The response is consistently one update behind.\n\n"
        "Cause: `ConfigurationService.update()` builds the response with "
        "`mapper.toResponse(saved)` while still inside the transaction, whereas "
        "`AuditEntityListener.@PreUpdate` stamps `updatedAt`/`updatedBy` at flush/commit — "
        "after the DTO has already been read off the entity.\n\n"
        "The persisted value **is** correct (`TC-BE-CU-008` itself passes when the row is "
        "read back), so `AuditEntityListener` works and no data is wrong; what is wrong is "
        "what the endpoint tells the client. A UI that renders the PUT response shows a "
        "stale 'last modified' until it refetches. The same map-before-commit shape is the "
        "`build-create-service` house pattern, so the defect is very likely present in every "
        "module's update endpoint, not just CU — worth checking platform-wide. No production "
        "code was touched by this run.",
    ),
    (
        "TC-BE-CU-006 — configKey change attempt",
        "test assumption mismatch — the manifest triple is unsatisfiable by design "
        "(NOT an application bug), with one real usability concern attached",
        "The manifest states `RULE-CU-003 | ERR-0003 | TC-BE-CU-006 | 422`, so that is what "
        "was asserted verbatim. The endpoint answered **HTTP 200** with no error code.\n\n"
        "The rule itself is nevertheless honoured, and the companion assertion "
        "`TC-BE-CU-006 (effect)` proves it: after the attempt, the original key still "
        "resolves and the attempted new key returns 404 — `configKey` was not mutated. "
        "CU's own artifacts already say this is by design: `ConfigurationUpdateRequest` "
        "excludes `configKey` at the DTO layer (DATA-DOM / SVC-API), and the "
        "`APP_CONFIGURATION_KEY_IMMUTABLE` constant's javadoc in `CuErrorCodes` states it is "
        "'registered for catalog completeness; unused by any throw site because enforcement "
        "is structural'. So the 422 the manifest promises can never be produced, and the "
        "api-docs publish a fourth error code that no call can return.\n\n"
        "**The real concern, separate from the status code:** the unknown `configKey` "
        "property is accepted silently (stage-E observation), so a client that believes it "
        "renamed a configuration receives a 200 and a response body showing the *old* key. "
        "Failing closed (422/400) would tell it the truth. That is a design decision for a "
        "human, not something this run may change.",
    ),
]

# Divergences found between the governed documents and the live surface that carry no
# assertion of their own — reported so a human can reconcile the documents.
DOC_FINDINGS: list[str] = [
    "**api-docs, all four write endpoints** — `POST /api/v1/common/configurations` is "
    "documented as `Response 200 — OK`, but the endpoint returns **201 Created** "
    "(`ServiceResult.success(..., Status.CREATED)`, and index.md's own "
    "'Status -> HTTP Status Reference' maps CREATED -> 201). This is springdoc's default "
    "200 leaking into the generated doc; the test asserts 201, per the test plan and that "
    "mapping table.",
    "**api-verify-config.md §3 vs CU's runtime codes** — the config states the error-code "
    "format `{MOD}-{http}[-{SLUG}]` (e.g. `SEC-409-USER-DUP`). CU emits descriptive codes "
    "instead (`APP_CONFIGURATION_KEY_DUPLICATE`, ...), deliberately: `CuErrorCodes`' javadoc "
    "cites gov-enforce-error-handling's `<ENTITY>_<SCENARIO>` format. Two governance "
    "documents disagree about the project-wide code format; SEC's own codes (observed here: "
    "`SEC-401-INVALID-CREDENTIALS`) follow the config's format, so the divergence is real "
    "and module-by-module, not a CU quirk. Needs a human reconciliation.",
    "**api-verify-config.md §3 vs the actual error envelope** — the config describes "
    "`{code, messageAr, messageEn}`. The live envelope is "
    "`{code, message, fieldErrors}` — a single `message`, resolved from the request's "
    "`Accept-Language` (verified: the same 404 returns 'الإعداد غير موجود.' under `ar` and "
    "'Configuration not found.' under `en`). Both languages are reachable, but not "
    "simultaneously in one response, so an `messageAr`/`messageEn` assertion would be "
    "wrong against this stack. The language assertions here send two requests instead.",
    "**backend-test-plan TC-BE-CU-007 / TC-BE-CU-012** — both describe search as "
    "`GET /api/v1/common/configurations?configKey=...&page=0&size=10`. No such GET endpoint "
    "exists; the api-docs (and the controller) document `POST "
    "/api/v1/common/configurations/search` with a filters/sort/page body. The api-docs are "
    "authoritative per the skill, so the script uses POST /search with a "
    "`{field: configKey, operator: LIKE}` filter. Documentation finding against the plan.",
    "**backend-test-plan TC-BE-CU-001** — expects `appConfigurationPk` and `isActiveFl` in "
    "the response. The live `ConfigurationResponse` exposes `id` and `isActive` "
    "(`isActiveFl` is the DB column name, per api-verify-config.md §3's DELETE-semantics "
    "row). The script asserts the api-docs' field names.",
    "**Permission gating absent** — api-verify-config.md §3 describes a "
    "`PERM_<PAGE_CODE>_<ACTION>` permission model for every module. CU has none in force: "
    "every `@PreAuthorize(hasAuthority(PermissionConstants.CONFIG_*))` in "
    "`ConfigurationService` is commented out behind a `TODO: SEC-PENDING` marker, CU has no "
    "row in `SEC_MODULE_REG`, and no `CONFIG_*` screen or action is registered. Any "
    "authenticated user can therefore create, update and deactivate platform configuration. "
    "Unauthenticated access IS blocked (401, observed). Flagged as a governance gap, not "
    "asserted — no artifact states CU's intended permission codes.",
    "**index.md pagination envelope** — the table omits `content`, which every search "
    "response carries (verified in preflight). Minor generator gap.",
]


# Residue created by this session OUTSIDE the script's tracked-id set (a manual diagnostic
# probe). Kept here so a regeneration of the report does not erase the disclosure.
SESSION_RESIDUE: list[str] = [
    "`PROBE_AUDIT_12644` (id=5) — created by a manual `curl` probe while diagnosing the "
    "TC-BE-CU-008 finding, not by this script, so the tracked-id set never held it. Retired "
    "afterwards through the documented `DELETE /api/v1/common/configurations/{key}` "
    "(HTTP 204); `CU_APP_CONFIGURATION` held zero active rows after that call.",
    "`PROBE_KEY_61874` (id=14) — an **ACTIVE** row this run did not create and did not "
    "touch. It appeared in `CU_APP_CONFIGURATION` between two iterations of this script, "
    "so it belongs to another session running against the same database. Disclosed rather "
    "than cleaned up: the api-verify skill forbids mutating a record the run did not "
    "create. A human may retire it with "
    "`DELETE /api/v1/common/configurations/PROBE_KEY_61874`.",
]


def write_report(path: str):
    total_p = sum(s.passed_count for s in SUITES)
    total_f = sum(s.failed_count for s in SUITES)
    lines = [
        "# CU — api-verify problems report",
        "",
        f"Generated: {date.today().isoformat()} · RUN_ID `{RUN_ID}` · tier **Full** "
        f"(api-docs + P3_5_BE/test-execution-manifest.md both present)",
        f"Target: `{BASE_URL}` (Dev/Test — localhost, per api-verify-config.md §4.1)",
        "",
        f"**{total_p} passed · {total_f} failed** across {len(SUITES)} suites · "
        f"{len(OBSERVATIONS)} observation(s), which never affect the totals.",
        "",
        "## Suites",
        "",
        "| Suite | Passed | Failed |",
        "|---|---|---|",
    ]
    for s in SUITES:
        lines.append(f"| {s.entity} | {s.passed_count} | {s.failed_count} |")

    lines += ["", "## Failures", ""]
    fails = [(s, r) for s in SUITES for r in s.results if not r.passed]
    if not fails:
        lines.append("_None._")
    else:
        lines.append("| Suite | Test | Detail | Response |")
        lines.append("|---|---|---|---|")
        for s, r in fails:
            det = r.detail.replace("|", "\\|")[:300]
            snip = (r.response_snippet or "").replace("|", "\\|")[:200]
            lines.append(f"| {s.entity} | {r.name} | {det} | `{snip}` |")

    lines += ["", "## Stage G — failure classification", ""]
    if not fails:
        lines.append("_No failures to classify._")
    else:
        for r_name, bucket, analysis in CLASSIFICATIONS:
            if not any(r.name.startswith(r_name) for _, r in fails):
                continue
            lines += [f"### {r_name}", "", f"**Bucket: {bucket}**", "", analysis, ""]

    lines += ["", "## Documentation findings (no assertion attached)", ""]
    lines += [f"- {d}" for d in DOC_FINDINGS]

    lines += ["", "## Preconditions (stage A0)", ""]
    lines += ([f"- {p}" for p in PRECONDITION_FAILURES]
              or ["_All preconditions satisfied. CU's payloads reference no externally-owned "
                  "value (no FK, no lookup key, no owner-module code), so stage A0 verified "
                  "reachability, key availability and the documented page envelope only._"])

    lines += ["", "## Observations (stage E — not pass/fail)", ""]
    lines += ([f"- **{o.name}** — {o.detail}" for o in OBSERVATIONS] or ["_None._"])

    lines += ["", "## Surviving records", ""]
    lines += ([f"- {n}" for n in LEFT_BEHIND] or ["_None._"])

    lines += ["", "### Residue from this session outside the script's own tracking", ""]
    lines += ([f"- {n}" for n in SESSION_RESIDUE] or ["_None._"])

    lines += ["", "### Permanent residue (reference data other modules read)", ""]
    lines += ([f"- {n}" for n in PERMANENT_RESIDUE]
              or ["_None — every row this run created was confirmed deactivated._"])

    lines += [
        "", "## Privileges",
        "",
        "No permission grant was created or revoked by this run, and no grant journal was "
        "written. CU's endpoints are authenticated but not permission-gated at the time of "
        "this run: every `@PreAuthorize(hasAuthority(PermissionConstants.CONFIG_*))` on "
        "`ConfigurationService` is commented out behind a `TODO: SEC-PENDING` marker, and "
        "CU registers no module row in `SEC_MODULE_REG` and no `CONFIG_*` screen or action "
        "in SEC's registries — so no CU permission exists to grant or to hold. Stage I was "
        "skipped entirely and **no standing privilege was left behind**.",
        "",
    ]
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"\nReport written: {path}")


# ══════════════════════════════════════════════════════════════════
# main
# ══════════════════════════════════════════════════════════════════


def main() -> int:
    global BASE_URL
    if len(sys.argv) > 1:
        BASE_URL = sys.argv[1].rstrip("/")

    c = APIClient(BASE_URL)
    print(f"api-verify — CU · tier Full · RUN_ID={RUN_ID} · target {BASE_URL}")

    tok = c.login(ADMIN_USERNAME, ADMIN_PASSWORD)
    if not tok:
        print("FATAL: could not authenticate — ENVIRONMENT_FAILURE", file=sys.stderr)
        return 2
    c.token = tok

    try:
        grants(c)        # stage I — no-op for CU, see the function's docstring
        preflight(c)     # stage A0
        test_app_configuration(c)   # stage B order #1 (the only entity)
    finally:
        try:
            cleanup(c)
        except Exception as e:  # noqa: BLE001
            print(f"cleanup FAILED: {e}")
        write_report(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                  "cu_problems_report.md"))

    total_f = sum(s.failed_count for s in SUITES)
    print(f"\nTOTAL: {sum(s.passed_count for s in SUITES)} passed, {total_f} failed")
    return 1 if total_f else 0


if __name__ == "__main__":
    raise SystemExit(main())
