#!/usr/bin/env python3
# Intended for Dev/Test environments only.
"""
api-verify — Post-Implementation API Verification Script for the NOTIF module.

Generated by the `api-verify` skill (.claude/skills/api-verify/SKILL.md), Full tier
(api-docs + P3_5_BE/test-execution-manifest.md both present).

Translation, not derivation: every path, payload value, error code and dependency edge
below is traceable to one of the inputs named here. Nothing is invented.

Inputs translated:
  - governance/modules/NOTIF/api-docs/index.md + endpoints/*.md   (regenerated this run)
  - governance/modules/NOTIF/P3_5_BE/test-execution-manifest.md
        -> DEPENDENCY ORDER (stage B), RULE -> ERR -> TC triples (stage C),
           ENTITY CRUD CHECKLIST
  - governance/modules/NOTIF/P3_5_BE/backend-test-plan.md   (TC-BE-NOTIF-001..016)
  - governance/api-verify-config.md                          (stack conventions)

Concurrency: two sibling verification runs (CU, FILE) share this database. Every value this
run writes carries the RUN_ID suffix, and no assertion reads a global count or "the first row" —
log assertions filter on this run's own `referenceType`.

Run: python3 governance/modules/NOTIF/test-api/test_notif_apis.py [BASE_URL]
"""

from __future__ import annotations

import json
import os
import sys
import time
from dataclasses import dataclass, field
from datetime import date
from typing import Any, Optional

import requests

BASE_URL = "http://localhost:7272"
# Documented Dev/Test bootstrap credential (CLAUDE.md "Running Locally" / memory: admin/admin).
# Overridable by run arguments; never a production secret.
ADMIN_USERNAME = os.environ.get("NOTIF_VERIFY_USER", "admin")
ADMIN_PASSWORD = os.environ.get("NOTIF_VERIFY_PASS", "admin")

# Run-scoped suffix. NOTIF documents no hard-delete endpoint for any entity
# (ENTITY CRUD CHECKLIST: template = soft "(flag)", channel = enable/disable, log = read-only),
# so rows from a prior run persist and would collide on the unique templateCode constraint.
# Only uniqueness is appended; every business value itself comes from an api-docs Example.
RUN_ID = str(int(time.time()))[-6:]

# api-docs examples, run-scoped where a unique constraint or a run-scoped query needs it.
TEMPLATE_CODE = f"USER_WELCOME_{RUN_ID}"          # example: USER_WELCOME
TEMPLATE_CODE_INACTIVE = f"USER_WELCOME_X_{RUN_ID}"
CHANNEL_TYPE_ENABLED = "SMS"                       # example: channelHint ["EMAIL", "SMS"]
# NOTIF_CHANNEL_CONFIG.CHANNEL_TYPE_ID is UNIQUE and the module documents no hard delete, so the
# channel type a previous run created still exists (disabled). This run will not mutate a record
# it did not create, so it falls back through the remaining LOV-NOTIF-001 values — all verified
# active in preflight, none invented — until it finds one it can own. EMAIL is excluded on
# purpose: it is seeded, and it is the one channel backed by a real SMTP provider.
CHANNEL_TYPE_CANDIDATES = ["SMS", "WHATSAPP", "PUSH", "INTERNAL"]
CHANNEL_TYPE_EMAIL = "EMAIL"                       # example: channelTypeId EMAIL
MODULE_CODE = "SEC"                                # example: moduleCode SEC
REFERENCE_TYPE = f"USER_ACCOUNT_{RUN_ID}"          # example: USER_ACCOUNT — run-scoped so the
                                                   # log search only ever sees this run's rows
REFERENCE_ID = 1001                                # example: referenceId 1001
SQLI_MODULE_CODE = "x' OR '1'='1"                  # TC-BE-NOTIF-016, verbatim from the test plan

# Documented lookup keys (NOTIF_CHANNEL = LOV-NOTIF-001, NOTIF_STATUS = LOV-NOTIF-002);
# both named in the api-docs response field descriptions for channelTypeId / notificationStatusId.
LOOKUP_CHANNEL = "NOTIF_CHANNEL"
LOOKUP_STATUS = "NOTIF_STATUS"

# ══════════════════════════════════════════════════════════════════
# Result plumbing
# ══════════════════════════════════════════════════════════════════


@dataclass
class TestResult:
    name: str
    passed: bool
    detail: str
    response_snippet: str = ""


@dataclass
class TestSuite:
    entity: str
    results: list[TestResult] = field(default_factory=list)

    @property
    def passed_count(self) -> int:
        return sum(1 for r in self.results if r.passed)

    @property
    def failed_count(self) -> int:
        return sum(1 for r in self.results if not r.passed)


@dataclass
class Observation:
    name: str
    detail: str
    response_snippet: str = ""


SUITES: list[TestSuite] = []
OBSERVATIONS: list[Observation] = []
PRECONDITION_FAILURES: list[str] = []
_current_suite: Optional[TestSuite] = None


def start_suite(entity: str) -> TestSuite:
    global _current_suite
    s = TestSuite(entity=entity)
    SUITES.append(s)
    _current_suite = s
    print(f"\n=== {entity} ===")
    return s


def run(name: str, fn):
    """Executes fn(); records pass/fail. fn returns (bool, detail, snippet)."""
    assert _current_suite is not None, "run() called before start_suite()"
    try:
        ok, detail, snip = fn()
    except AssertionError as e:
        ok, detail, snip = False, f"AssertionError: {e}", ""
    except Exception as e:  # noqa: BLE001
        ok, detail, snip = False, f"EXCEPTION: {type(e).__name__}: {e}", ""
    r = TestResult(name=name, passed=ok, detail=detail, response_snippet=snip)
    _current_suite.results.append(r)
    print(f"  [{'PASS' if ok else 'FAIL'}] {name} — {detail}")
    return r


def run_observation(name: str, fn):
    """Stage E — outcome not governed by a RULE + code. Never affects totals."""
    try:
        _, detail, snip = fn()
    except Exception as e:  # noqa: BLE001
        detail, snip = f"EXCEPTION: {type(e).__name__}: {e}", ""
    o = Observation(name=name, detail=detail, response_snippet=snip)
    OBSERVATIONS.append(o)
    print(f"  [OBS ] {name} — {detail}")
    return o


def blocked(name: str, why: str):
    """Records a test that could not run because a precondition failed."""
    assert _current_suite is not None
    r = TestResult(name=name, passed=False, detail=f"BLOCKED-ON-PRECONDITION: {why}")
    _current_suite.results.append(r)
    print(f"  [BLK ] {name} — {why}")
    return r


# ══════════════════════════════════════════════════════════════════
# API client — ApiResponse<T> envelope per api-verify-config.md §3
# ══════════════════════════════════════════════════════════════════


class APIClient:
    def __init__(self, base_url: str = BASE_URL):
        self.base_url = base_url
        self.token: Optional[str] = None
        self.session = requests.Session()

    def _headers(self, token: Optional[str] = None, lang: Optional[str] = None,
                 anonymous: bool = False) -> dict:
        h = {"Content-Type": "application/json"}
        tok = None if anonymous else (token if token is not None else self.token)
        if tok:
            h["Authorization"] = f"Bearer {tok}"
        if lang:
            h["Accept-Language"] = lang
        return h

    def _make(self, method, path, json_body=None, params=None, token=None,
              lang=None, anonymous=False, timeout=60):
        return self.session.request(
            method, f"{self.base_url}{path}", json=json_body, params=params,
            headers=self._headers(token, lang, anonymous), timeout=timeout,
        )

    def get(self, path, params=None, token=None, lang=None, anonymous=False):
        return self._make("GET", path, params=params, token=token, lang=lang, anonymous=anonymous)

    def post(self, path, json_body=None, token=None, lang=None, anonymous=False):
        return self._make("POST", path, json_body=json_body, token=token, lang=lang,
                          anonymous=anonymous)

    def put(self, path, json_body=None, token=None, lang=None):
        return self._make("PUT", path, json_body=json_body, token=token, lang=lang)

    def delete(self, path, token=None):
        return self._make("DELETE", path, token=token)

    def login(self, username: str, password: str) -> Optional[str]:
        r = self.post("/api/v1/sec/auth/login",
                      {"username": username, "password": password})
        if r.status_code == 200:
            return ((r.json().get("data")) or {}).get("accessToken")
        return None


def data_of(resp) -> Any:
    try:
        return resp.json().get("data")
    except Exception:  # noqa: BLE001
        return None


def field_of(resp, key) -> Any:
    d = data_of(resp)
    return d.get(key) if isinstance(d, dict) else None


def err_code(resp) -> Optional[str]:
    try:
        return (resp.json().get("error") or {}).get("code")
    except Exception:  # noqa: BLE001
        return None


def snippet(resp, limit: int = 300) -> str:
    try:
        return json.dumps(resp.json(), ensure_ascii=False)[:limit]
    except Exception:  # noqa: BLE001
        return (resp.text or "")[:limit]


def expect_status(resp, want: int, what: str):
    return (resp.status_code == want,
            f"{what}: HTTP {resp.status_code} (want {want})", snippet(resp))


def expect_error(resp, want_status: int, want_code: str, what: str):
    got = err_code(resp)
    ok = resp.status_code == want_status and got == want_code
    return (ok,
            f"{what}: HTTP {resp.status_code}/{got} (want {want_status}/{want_code})",
            snippet(resp))


def field_errors(resp) -> list:
    """The `error.fieldErrors` array of the platform validation envelope (may be absent/null)."""
    try:
        return (resp.json().get("error") or {}).get("fieldErrors") or []
    except Exception:  # noqa: BLE001
        return []


def expect_validation_field(resp, want_field: str, what: str):
    """Assert the platform's deliberate bean-validation refusal: HTTP 400, wire code
    `VALIDATION_ERROR`, and a `fieldErrors` entry naming `want_field`.

    This is GlobalExceptionHandler.handleValidation's documented shape. Asserting the field
    name (not just the status) is what keeps such a test meaningful: it still proves the rule
    is enforced AND on which field, which the generic per-module business code cannot express
    because it carries no per-field detail and reports only one failure at a time.
    """
    got = err_code(resp)
    fields = [fe.get("field") for fe in field_errors(resp)]
    ok = (resp.status_code == 400
          and got == "VALIDATION_ERROR"
          and want_field in fields)
    return (ok,
            f"{what}: HTTP {resp.status_code}/{got}, fieldErrors={fields} "
            f"(want 400/VALIDATION_ERROR naming '{want_field}')",
            snippet(resp))


# ══════════════════════════════════════════════════════════════════
# Stage F — created-entity tracking
# ══════════════════════════════════════════════════════════════════

created: dict[str, list] = {
    "NotificationTemplate": [],     # soft deactivate only (DELETE = flip isActiveFl)
    "NotificationChannelConfig": [],  # soft disable only (DELETE = flip isEnabledFl)
    "NotificationLog": [],          # no delete or deactivate surface at all — read-only screen
}

LEFT_BEHIND: list[str] = []
PERMANENT_RESIDUE: list[str] = []

# Shared context threaded between suites (FK ids and ids read back from a create, never literals).
ctx: dict[str, Any] = {}


# ══════════════════════════════════════════════════════════════════
# Stage I — permission preconditions
# ══════════════════════════════════════════════════════════════════


def grants(c: APIClient):
    """Stage I — NOT exercised, and deliberately so.

    Every NOTIF service method carries a commented-out authority check
    (`// TODO: SEC-PENDING — re-add @PreAuthorize(hasAuthority(PermissionConstants.PERM_NOTIF_*))`,
    src/main/java/com/erp/notif/service/*.java), so no NOTIF endpoint is gated by a
    PERM_NOTIF_* permission at all today; the only live gate is the platform
    `isAuthenticated()` on DispatchService and NotificationLookupService.
    There is therefore nothing this run could need to grant itself, no journal entry is
    written, and no standing privilege can be left behind. Reported either way (SKILL.md §3-I).
    """
    return


# ══════════════════════════════════════════════════════════════════
# Stage A0 — preconditions
# ══════════════════════════════════════════════════════════════════


def preflight(c: APIClient):
    """Every externally-owned value the payloads reference is verified present and active
    before the suites that need it. Order is grants -> preconditions -> suites; this run
    needs no grant (see grants())."""
    start_suite("PREFLIGHT (stage A0)")

    def channel_lov():
        r = c.get(f"/api/v1/notifications/lookups/{LOOKUP_CHANNEL}")
        vals = data_of(r) or []
        codes = [v.get("code") for v in vals] if isinstance(vals, list) else []
        ctx["channel_codes"] = codes
        missing = [x for x in (CHANNEL_TYPE_EMAIL, CHANNEL_TYPE_ENABLED) if x not in codes]
        if missing:
            PRECONDITION_FAILURES.append(
                f"{LOOKUP_CHANNEL}: missing active value(s) {missing} — the dispatch api-docs "
                f"example channelHint ['EMAIL','SMS'] references them")
        return (r.status_code == 200 and not missing,
                f"{LOOKUP_CHANNEL}: {len(codes)} active value(s); missing={missing or 'none'}",
                ",".join(codes))

    run(f"MDL-owned lookup '{LOOKUP_CHANNEL}' resolves via NOTIF (XM: MdlLookupApi)", channel_lov)

    def status_lov():
        r = c.get(f"/api/v1/notifications/lookups/{LOOKUP_STATUS}")
        vals = data_of(r) or []
        codes = [v.get("code") for v in vals] if isinstance(vals, list) else []
        ctx["status_codes"] = codes
        # The four statuses the api-docs' own notificationStatusId description and the test plan
        # name: PENDING (initial), SENT, FAILED, CHANNEL_DISABLED.
        wanted = ["PENDING", "SENT", "FAILED", "CHANNEL_DISABLED"]
        missing = [x for x in wanted if x not in codes]
        if missing:
            PRECONDITION_FAILURES.append(
                f"{LOOKUP_STATUS}: missing active value(s) {missing} — dispatch writes them as "
                f"notificationStatusId")
        return (r.status_code == 200 and not missing,
                f"{LOOKUP_STATUS}: {len(codes)} active value(s); missing={missing or 'none'}",
                ",".join(codes))

    run(f"MDL-owned lookup '{LOOKUP_STATUS}' resolves via NOTIF (XM: MdlLookupApi)", status_lov)

    def recipient():
        """recipientId is an externally-owned SEC UserAccount id. The api-docs example is 42;
        NOTIF documents no endpoint to verify it, so it is resolved through SEC's own documented
        search endpoint instead of being trusted as a literal (SKILL.md §3-A0)."""
        r = c.post("/api/v1/sec/users/search", {"page": 0, "size": 200})
        content = (data_of(r) or {}).get("content") or []
        active = [u for u in content if u.get("isActiveFl") is True]
        inactive = [u for u in content if u.get("isActiveFl") is False]
        if active:
            ctx["recipient_id"] = active[0].get("userPk")
        if inactive:
            ctx["inactive_recipient_id"] = inactive[0].get("userPk")
        if not active:
            PRECONDITION_FAILURES.append(
                "no ACTIVE SEC user account found — dispatch suites cannot bind a real recipientId")
        return (bool(active),
                f"recipientId resolved from SEC: active={ctx.get('recipient_id')}, "
                f"inactive={ctx.get('inactive_recipient_id')} "
                f"(api-docs example 42 not used as a literal)",
                snippet(r, 120))

    run("recipientId (SEC UserAccount, XM-NOTIF-001) resolved and verified active", recipient)

    def email_channel_state():
        """The EMAIL channel config is pre-existing seed data (id 1) this run must not mutate.
        Its enabled state decides what an EMAIL dispatch does, so it is read, never written."""
        r = c.post("/api/v1/notifications/channels/search",
                   {"filters": [{"field": "channelTypeId", "operator": "EQUALS",
                                 "value": CHANNEL_TYPE_EMAIL}], "page": 0, "size": 50})
        content = (data_of(r) or {}).get("content") or []
        mine = [x for x in content if x.get("channelTypeId") == CHANNEL_TYPE_EMAIL]
        if mine:
            ctx["email_channel_enabled"] = mine[0].get("isEnabledFl")
            ctx["email_channel_id"] = mine[0].get("id")
        return (r.status_code == 200,
                f"pre-existing EMAIL channel config: id={ctx.get('email_channel_id')}, "
                f"isEnabledFl={ctx.get('email_channel_enabled')} (read-only, never mutated here)",
                snippet(r, 200))

    run("pre-existing EMAIL channel config read (not mutated)", email_channel_state)


# ══════════════════════════════════════════════════════════════════
# 1. NotificationTemplate  (manifest DEPENDENCY ORDER #1 — parent, independent)
# ══════════════════════════════════════════════════════════════════


def test_template(c: APIClient):
    """Covers: API-NOTIF-004 (templates CRUD + search)
    Negative: RULE-NOTIF-004 / NOTIF_TEMPLATE_BILINGUAL_REQUIRED / TC-BE-NOTIF-006 ;
              RULE-NOTIF-006 / NOTIF_TEMPLATE_CODE_DUPLICATE / TC-BE-NOTIF-009 (template half) ;
              (PLATFORM) / NOTIF_TEMPLATE_NOT_FOUND / TC-BE-NOTIF-013 (404 shape)
    Also: TC-BE-NOTIF-005 (bilingual accepted), TC-BE-NOTIF-008 (unique code accepted),
          TC-BE-NOTIF-014 (CRUD happy)."""
    start_suite("NotificationTemplate")

    body = {
        "templateCode": TEMPLATE_CODE,
        "nameAr": "ترحيب بالمستخدم",
        "nameEn": "User Welcome",
        "subjectAr": "مرحبًا بك",
        "subjectEn": "Welcome",
        "bodyAr": "أهلًا {0}",
        "bodyEn": "Hello {0}",
        "isActiveFl": True,
    }
    # attachmentFileId (api-docs example 1001) is deliberately omitted: it is optional, the FILE
    # cross-module validation is XM-NOTIF-002 DEFERRED, and 1001 is not a verified FILE_DOCUMENT id.

    def create():
        r = c.post("/api/v1/notifications/templates", body)
        tid = field_of(r, "id")
        if tid:
            created["NotificationTemplate"].append(tid)
            ctx["template_id"] = tid
        # ENTITY CRUD CHECKLIST + ServiceResult Status.CREATED -> 201 per the shared
        # Status->HTTP table in api-docs/index.md (the api-docs' own "Response 200" block is
        # springdoc's default, not a declared contract).
        ok = r.status_code in (200, 201) and field_of(r, "templateCode") == TEMPLATE_CODE
        return ok, f"TC-BE-NOTIF-005/008: HTTP {r.status_code}, id={tid}", snippet(r)

    run("TC-BE-NOTIF-005/008 — create template with both bodies and a unique code", create)

    tid = ctx.get("template_id")
    if not tid:
        blocked("TC-BE-NOTIF-014 template CRUD", "create returned no id")
        return

    run("TC-BE-NOTIF-014 — get template by id",
        lambda: expect_status(c.get(f"/api/v1/notifications/templates/{tid}"), 200, "getById"))

    run("TC-BE-NOTIF-013 — unknown template id -> 404 NOTIF_TEMPLATE_NOT_FOUND",
        lambda: expect_error(c.get("/api/v1/notifications/templates/99999999"),
                             404, "NOTIF_TEMPLATE_NOT_FOUND", "getById unknown"))

    def update():
        upd = {k: v for k, v in body.items() if k != "templateCode"}
        upd["nameEn"] = "User Welcome Updated"
        r = c.put(f"/api/v1/notifications/templates/{tid}", upd)
        return (r.status_code == 200 and field_of(r, "nameEn") == "User Welcome Updated",
                f"update: HTTP {r.status_code}", snippet(r))

    run("TC-BE-NOTIF-014 — update template", update)

    def search():
        r = c.post("/api/v1/notifications/templates/search",
                   {"filters": [{"field": "templateCode", "operator": "EQUALS",
                                 "value": TEMPLATE_CODE}], "page": 0, "size": 20})
        d = data_of(r) or {}
        codes = [x.get("templateCode") for x in (d.get("content") or [])]
        return (r.status_code == 200 and TEMPLATE_CODE in codes,
                f"search by this run's own templateCode: HTTP {r.status_code}, "
                f"found={TEMPLATE_CODE in codes}, totalElements={d.get('totalElements')}",
                snippet(r, 200))

    run("TC-BE-NOTIF-014 — search finds this run's template", search)

    # Stage C — RULE-NOTIF-006 / ERR-0002 / TC-BE-NOTIF-009 (template half), 409.
    run("TC-BE-NOTIF-009 — duplicate templateCode -> 409 NOTIF_TEMPLATE_CODE_DUPLICATE",
        lambda: expect_error(c.post("/api/v1/notifications/templates", body),
                             409, "NOTIF_TEMPLATE_CODE_DUPLICATE", "duplicate code"))

    # Stage C — RULE-NOTIF-004 / TC-BE-NOTIF-006, 400, on CREATE and on UPDATE.
    # The governed code ERR-0001 `NOTIF_TEMPLATE_BILINGUAL_REQUIRED` is UNREACHABLE over HTTP,
    # and deliberately so: TemplateCreateRequest/TemplateUpdateRequest both carry @NotBlank on
    # bodyAr and bodyEn, so Spring bean validation refuses at the controller boundary before
    # NotificationTemplateDomain — the throw site of ERR-0001 — is ever entered. The platform's
    # documented mechanism for that refusal is GlobalExceptionHandler.handleValidation: HTTP
    # 400, wire code VALIDATION_ERROR, and a per-field `fieldErrors` entry, which preserves
    # detail the single generic domain code cannot (WHICH body is missing, and every failing
    # field reported at once). Asserting the field name keeps RULE-NOTIF-004 proven: both
    # language bodies are still mandatory, and the refusal still names the missing one.
    def missing_body_en():
        payload = dict(body)
        payload["templateCode"] = f"MISSING_EN_{RUN_ID}"
        payload.pop("bodyEn")
        r = c.post("/api/v1/notifications/templates", payload)
        if r.status_code in (200, 201):
            tid2 = field_of(r, "id")
            if tid2:
                created["NotificationTemplate"].append(tid2)
        return expect_validation_field(r, "bodyEn", "missing bodyEn")

    run("TC-BE-NOTIF-006 (create) — template without bodyEn -> 400 VALIDATION_ERROR naming "
        "`bodyEn` (RULE-NOTIF-004; ERR-0001 NOTIF_TEMPLATE_BILINGUAL_REQUIRED is structurally "
        "unreachable — @NotBlank refuses first)",
        missing_body_en)

    # Same rule on UPDATE — same structural reason, the mirrored @NotBlank on
    # TemplateUpdateRequest.bodyAr, so the Domain re-validation in
    # NotificationTemplateService.update is likewise never reached from HTTP.
    def update_missing_body_ar():
        upd = {k: v for k, v in body.items() if k != "templateCode"}
        upd.pop("bodyAr")
        return expect_validation_field(
            c.put(f"/api/v1/notifications/templates/{tid}", upd),
            "bodyAr", "update without bodyAr")

    run("TC-BE-NOTIF-006 (update) — update dropping bodyAr -> 400 VALIDATION_ERROR naming "
        "`bodyAr` (RULE-NOTIF-004; ERR-0001 NOTIF_TEMPLATE_BILINGUAL_REQUIRED is structurally "
        "unreachable — @NotBlank refuses first)",
        update_missing_body_ar)

    # A second template, deactivated on purpose, so the dispatch suite can exercise the
    # documented NOTIF_TEMPLATE_INACTIVE path without retiring the main fixture.
    def create_inactive_fixture():
        payload = dict(body)
        payload["templateCode"] = TEMPLATE_CODE_INACTIVE
        r = c.post("/api/v1/notifications/templates", payload)
        tid2 = field_of(r, "id")
        if tid2:
            created["NotificationTemplate"].append(tid2)
            ctx["template_inactive_id"] = tid2
            d = c.delete(f"/api/v1/notifications/templates/{tid2}")
            ctx["template_inactive_deactivated"] = d.status_code == 204
            return (r.status_code in (200, 201) and d.status_code == 204,
                    f"create HTTP {r.status_code}, deactivate HTTP {d.status_code} (want 204)",
                    snippet(d))
        return False, f"create failed HTTP {r.status_code}", snippet(r)

    run("TC-BE-NOTIF-014 — deactivate template returns 204 (soft, isActiveFl flipped)",
        create_inactive_fixture)

    def deactivated_is_readable():
        tid2 = ctx.get("template_inactive_id")
        r = c.get(f"/api/v1/notifications/templates/{tid2}")
        return (r.status_code == 200 and field_of(r, "isActiveFl") is False,
                f"deactivated template still readable with isActiveFl="
                f"{field_of(r, 'isActiveFl')} (soft delete per api-verify-config.md §3)",
                snippet(r))

    if ctx.get("template_inactive_id"):
        run("TC-BE-NOTIF-014 — DELETE is soft: the row survives with isActiveFl=false",
            deactivated_is_readable)

    # ── Stage E observations (required/constrained fields only) ──
    def over_length_code():
        payload = dict(body)
        payload["templateCode"] = ("C" * 81)          # maxLength 80
        r = c.post("/api/v1/notifications/templates", payload)
        if r.status_code in (200, 201) and field_of(r, "id"):
            created["NotificationTemplate"].append(field_of(r, "id"))
        return True, f"templateCode at 81 chars (max 80) -> HTTP {r.status_code}/{err_code(r)}", snippet(r)

    run_observation("stage E — templateCode one over its documented maxLength(80)", over_length_code)

    def deactivate_twice():
        tid2 = ctx.get("template_inactive_id")
        r = c.delete(f"/api/v1/notifications/templates/{tid2}")
        return True, f"second DELETE on an already-deactivated template -> HTTP {r.status_code}/{err_code(r)}", snippet(r)

    if ctx.get("template_inactive_id"):
        run_observation("stage E — DELETE idempotency on an already-deactivated template",
                        deactivate_twice)

    def unknown_sort_field():
        r = c.post("/api/v1/notifications/templates/search",
                   {"sortField": "notASortableField", "sortDirection": "ASC",
                    "page": 0, "size": 5})
        return True, f"unknown sortField -> HTTP {r.status_code}/{err_code(r)}", snippet(r, 200)

    run_observation("stage E — an undocumented sortField on template search", unknown_sort_field)

    def over_max_page_size():
        r = c.post("/api/v1/notifications/templates/search", {"page": 0, "size": 201})
        d = data_of(r) or {}
        return True, (f"size=201 (PageableBuilder max 200) -> HTTP {r.status_code}, "
                      f"returned size={d.get('size')}"), snippet(r, 150)

    run_observation("stage E — page size one over the documented maximum (200)", over_max_page_size)


# ══════════════════════════════════════════════════════════════════
# 2. NotificationChannelConfig  (manifest DEPENDENCY ORDER #2 — parent, independent)
# ══════════════════════════════════════════════════════════════════


def test_channel(c: APIClient):
    """Covers: API-NOTIF-005 (channels CRUD / enable-disable / search)
    Negative: RULE-NOTIF-006 / NOTIF_CHANNEL_CONFIG_DUPLICATE / TC-BE-NOTIF-009 (channel half) ;
              (PLATFORM) / NOTIF_CHANNEL_CONFIG_NOT_FOUND / TC-BE-NOTIF-013 (404 shape)
    Also: TC-BE-NOTIF-008 (unique channelTypeId accepted), TC-BE-NOTIF-015 (CRUD/enable)."""
    start_suite("NotificationChannelConfig")

    def create():
        global CHANNEL_TYPE_ENABLED
        taken = []
        for candidate in CHANNEL_TYPE_CANDIDATES:
            if candidate not in (ctx.get("channel_codes") or []):
                continue                      # not an active LOV-NOTIF-001 value on this target
            r = c.post("/api/v1/notifications/channels",
                       {"channelTypeId": candidate, "isEnabledFl": True})
            cid = field_of(r, "id")
            if r.status_code in (200, 201) and cid:
                CHANNEL_TYPE_ENABLED = candidate
                created["NotificationChannelConfig"].append(cid)
                ctx["channel_id"] = cid
                ctx["channel_created_by_this_run"] = True
                return (True,
                        f"TC-BE-NOTIF-008: HTTP {r.status_code}, id={cid}, "
                        f"channelTypeId={candidate}"
                        + (f" (skipped {taken}, already present from an earlier run)" if taken else ""),
                        snippet(r))
            if r.status_code == 409:
                taken.append(candidate)       # a previous run owns it; never mutated here
                continue
            return False, f"{candidate}: HTTP {r.status_code}/{err_code(r)}", snippet(r)
        PRECONDITION_FAILURES.append(
            f"every documented LOV-NOTIF-001 channel type {taken} already has a config row left "
            f"behind by an earlier run; this run will not mutate a record it did not create, so "
            f"the SENT-path dispatch checks are blocked. Purge them "
            f"(DELETE FROM NOTIF_CHANNEL_CONFIG WHERE CHANNEL_TYPE_ID IN ...) and rerun.")
        return False, f"no ownable channel type left (409 on {taken})", ""

    run("TC-BE-NOTIF-008 — create a channel config this run owns (enabled)", create)

    cid = ctx.get("channel_id")

    # Stage C — RULE-NOTIF-006 / ERR-0003 / TC-BE-NOTIF-009 (channel half), 409.
    # Uses the pre-existing seeded EMAIL config as the duplicate subject — a read-only collision,
    # nothing is written.
    run("TC-BE-NOTIF-009 — duplicate channelTypeId -> 409 NOTIF_CHANNEL_CONFIG_DUPLICATE",
        lambda: expect_error(
            c.post("/api/v1/notifications/channels",
                   {"channelTypeId": CHANNEL_TYPE_EMAIL, "isEnabledFl": True}),
            409, "NOTIF_CHANNEL_CONFIG_DUPLICATE", "duplicate channelTypeId"))

    run("TC-BE-NOTIF-013 — unknown channel id -> 404 NOTIF_CHANNEL_CONFIG_NOT_FOUND",
        lambda: expect_error(c.get("/api/v1/notifications/channels/99999999"),
                             404, "NOTIF_CHANNEL_CONFIG_NOT_FOUND", "getById unknown"))

    if not cid:
        blocked("TC-BE-NOTIF-015 channel CRUD", "no channel config created by this run")
        return

    run("TC-BE-NOTIF-015 — get channel config by id",
        lambda: expect_status(c.get(f"/api/v1/notifications/channels/{cid}"), 200, "getById"))

    def update():
        r = c.put(f"/api/v1/notifications/channels/{cid}",
                  {"isEnabledFl": True, "configJson": '{"provider":"stub"}'})
        return (r.status_code == 200 and field_of(r, "isEnabledFl") is True,
                f"update configJson: HTTP {r.status_code}, isEnabledFl={field_of(r, 'isEnabledFl')}",
                snippet(r))

    run("TC-BE-NOTIF-015 — update channel config", update)

    def search():
        r = c.post("/api/v1/notifications/channels/search",
                   {"filters": [{"field": "channelTypeId", "operator": "EQUALS",
                                 "value": CHANNEL_TYPE_ENABLED}], "page": 0, "size": 20})
        d = data_of(r) or {}
        ids = [x.get("id") for x in (d.get("content") or [])]
        return (r.status_code == 200 and cid in ids,
                f"search by this run's own channelTypeId: HTTP {r.status_code}, found={cid in ids}",
                snippet(r, 200))

    run("TC-BE-NOTIF-015 — search finds this run's channel config", search)

    # ── Stage E observations ──
    def over_length_channel_type():
        r = c.post("/api/v1/notifications/channels",
                   {"channelTypeId": "C" * 21, "isEnabledFl": True})   # maxLength 20
        if r.status_code in (200, 201) and field_of(r, "id"):
            created["NotificationChannelConfig"].append(field_of(r, "id"))
        return True, f"channelTypeId at 21 chars (max 20) -> HTTP {r.status_code}/{err_code(r)}", snippet(r)

    run_observation("stage E — channelTypeId one over its documented maxLength(20)",
                    over_length_channel_type)

    def missing_channel_type():
        r = c.post("/api/v1/notifications/channels", {"isEnabledFl": True})
        if r.status_code in (200, 201) and field_of(r, "id"):
            created["NotificationChannelConfig"].append(field_of(r, "id"))
        return True, (f"required channelTypeId omitted -> HTTP {r.status_code}/{err_code(r)} "
                      f"(NOTIF_CHANNEL_TYPE_REQUIRED is the module's own code for this)"), snippet(r)

    run_observation("stage E — required channelTypeId omitted on create", missing_channel_type)

    def undocumented_channel_value():
        # An LOV-NOTIF-001 value that the NOTIF_CHANNEL lookup does not carry.
        code = f"ZZ{RUN_ID}"
        r = c.post("/api/v1/notifications/channels", {"channelTypeId": code, "isEnabledFl": False})
        if r.status_code in (200, 201) and field_of(r, "id"):
            created["NotificationChannelConfig"].append(field_of(r, "id"))
            ctx["undocumented_channel_code"] = code
        return True, (f"channelTypeId '{code}' is not an active NOTIF_CHANNEL lookup value -> "
                      f"HTTP {r.status_code}/{err_code(r)}"), snippet(r)

    run_observation("stage E — a channelTypeId outside the NOTIF_CHANNEL lookup",
                    undocumented_channel_value)


# ══════════════════════════════════════════════════════════════════
# 3. Dispatch + NotificationLog  (manifest DEPENDENCY ORDER #3 — FK TEMPLATE_FK)
# ══════════════════════════════════════════════════════════════════


def test_dispatch(c: APIClient):
    """Covers: API-NOTIF-001 (dispatch)
    Negative/behavioural: RULE-NOTIF-001 (fan-out) TC-BE-NOTIF-001 ;
                          RULE-NOTIF-003 (CHANNEL_DISABLED) TC-BE-NOTIF-004 ;
                          (PLATFORM) NOTIF_TEMPLATE_NOT_FOUND TC-BE-NOTIF-013 ;
                          TC-BE-NOTIF-011 (202/{logIds}), TC-BE-NOTIF-015 (toggle affects dispatch),
                          TC-BE-NOTIF-016 (SQLi stored literal).
    Retry cases TC-BE-NOTIF-002/003 are recorded as observations — see the report."""
    start_suite("Dispatch")

    tid = ctx.get("template_id")
    rid = ctx.get("recipient_id")
    if not tid or not rid:
        blocked("TC-BE-NOTIF-001/011", "no active template or no verified recipient")
        return

    base = {
        "recipientId": rid,
        "templateCode": TEMPLATE_CODE,
        "moduleCode": MODULE_CODE,
        "referenceId": REFERENCE_ID,
        "referenceType": REFERENCE_TYPE,
    }
    # `variables` is optional in the api-docs and is deliberately not supplied: the EMAIL provider
    # reads the destination address from variables["email"], so omitting it guarantees this run
    # can never send mail to a real address through a live SMTP provider.

    def fan_out():
        """TC-BE-NOTIF-001 — exactly one NOTIF_LOG per requested channel."""
        r = c.post("/api/v1/notifications/dispatch",
                   dict(base, channelHint=[CHANNEL_TYPE_EMAIL, CHANNEL_TYPE_ENABLED]))
        ids = (data_of(r) or {}).get("logIds") or []
        created["NotificationLog"].extend(ids)
        ctx["fanout_log_ids"] = ids
        # The test plan states 202; the api-docs (and the shared Status->HTTP table) state 200.
        # Asserted against the api-docs, which api-verify-config.md §1 makes authoritative.
        return (r.status_code == 200 and len(ids) == 2,
                f"HTTP {r.status_code} (test plan says 202, api-docs say 200), "
                f"logIds={ids} (want exactly 2, one per requested channel)", snippet(r))

    run("TC-BE-NOTIF-001/011 — dispatch fans out one log per channelHint entry", fan_out)

    def sent_path():
        """The enabled, provider-backed channel this run created must reach SENT."""
        if not ctx.get("channel_created_by_this_run"):
            return False, "BLOCKED: this run created no enabled channel config", ""
        r = c.post("/api/v1/notifications/dispatch",
                   dict(base, channelHint=[CHANNEL_TYPE_ENABLED]))
        ids = (data_of(r) or {}).get("logIds") or []
        created["NotificationLog"].extend(ids)
        ctx["sent_log_id"] = ids[0] if ids else None
        if not ids:
            return False, f"HTTP {r.status_code}, no logIds returned", snippet(r)
        g = c.get(f"/api/v1/notifications/logs/{ids[0]}")
        status = field_of(g, "notificationStatusId")
        return (r.status_code == 200 and status == "SENT",
                f"log {ids[0]} notificationStatusId={status} (want SENT), "
                f"retryCount={field_of(g, 'retryCount')}", snippet(g))

    if ctx.get("channel_created_by_this_run"):
        run("TC-BE-NOTIF-015 — dispatch over an enabled channel reaches SENT", sent_path)
    else:
        blocked("TC-BE-NOTIF-015 — dispatch over an enabled channel reaches SENT",
                "no enabled channel config owned by this run")

    def disabled_channel():
        """TC-BE-NOTIF-004 / TC-BE-NOTIF-015 — flipping isEnabledFl changes the dispatch outcome."""
        cid = ctx.get("channel_id")
        if not cid:
            return False, "BLOCKED: no channel config owned by this run", ""
        d = c.delete(f"/api/v1/notifications/channels/{cid}")      # documented "disable"
        if d.status_code != 204:
            return False, f"disable endpoint returned HTTP {d.status_code}", snippet(d)
        ctx["channel_disabled"] = True
        r = c.post("/api/v1/notifications/dispatch",
                   dict(base, channelHint=[CHANNEL_TYPE_ENABLED]))
        ids = (data_of(r) or {}).get("logIds") or []
        created["NotificationLog"].extend(ids)
        if not ids:
            return False, f"HTTP {r.status_code}, no logIds returned", snippet(r)
        g = c.get(f"/api/v1/notifications/logs/{ids[0]}")
        status = field_of(g, "notificationStatusId")
        retry = field_of(g, "retryCount")
        return (status == "CHANNEL_DISABLED" and retry == 0,
                f"log {ids[0]} notificationStatusId={status} (want CHANNEL_DISABLED), "
                f"retryCount={retry} (want 0 — no retry, no provider call)", snippet(g))

    run("TC-BE-NOTIF-004/015 — a disabled channel yields CHANNEL_DISABLED with no retry",
        disabled_channel)

    run("TC-BE-NOTIF-013 — dispatch with an unknown templateCode -> 404 NOTIF_TEMPLATE_NOT_FOUND",
        lambda: expect_error(
            c.post("/api/v1/notifications/dispatch",
                   dict(base, templateCode=f"NO_SUCH_TEMPLATE_{RUN_ID}",
                        channelHint=[CHANNEL_TYPE_ENABLED])),
            404, "NOTIF_TEMPLATE_NOT_FOUND", "unknown templateCode"))

    def inactive_template():
        """NOTIF_TEMPLATE_INACTIVE — 422 BUSINESS_RULE_VIOLATION per api-docs Known Error Codes."""
        if not ctx.get("template_inactive_deactivated"):
            return False, "BLOCKED: no deactivated template fixture", ""
        return expect_error(
            c.post("/api/v1/notifications/dispatch",
                   dict(base, templateCode=TEMPLATE_CODE_INACTIVE,
                        channelHint=[CHANNEL_TYPE_ENABLED])),
            422, "NOTIF_TEMPLATE_INACTIVE", "dispatch on a deactivated template")

    run("TC-BE-NOTIF-014 — dispatch on a deactivated template -> 422 NOTIF_TEMPLATE_INACTIVE",
        inactive_template)

    def sqli_module_code():
        """TC-BE-NOTIF-016 — the SQLi string is stored as a literal and the DB stays intact."""
        r = c.post("/api/v1/notifications/dispatch",
                   dict(base, moduleCode=SQLI_MODULE_CODE, channelHint=[CHANNEL_TYPE_ENABLED]))
        ids = (data_of(r) or {}).get("logIds") or []
        created["NotificationLog"].extend(ids)
        if not ids:
            return False, f"HTTP {r.status_code}/{err_code(r)}, no logIds", snippet(r)
        g = c.get(f"/api/v1/notifications/logs/{ids[0]}")
        stored = field_of(g, "moduleCode")
        # DB intact: the lookup endpoint still resolves its five channel values afterwards.
        lk = c.get(f"/api/v1/notifications/lookups/{LOOKUP_CHANNEL}")
        intact = lk.status_code == 200 and len(data_of(lk) or []) == len(ctx.get("channel_codes") or [])
        return (stored == SQLI_MODULE_CODE and intact,
                f"moduleCode stored as {stored!r} (literal); lookups still resolve "
                f"{len(data_of(lk) or [])} values -> DB intact={intact}", snippet(g, 200))

    run("TC-BE-NOTIF-016 — SQLi moduleCode stored as a literal, DB intact", sqli_module_code)

    # ── Retry behaviour — TC-BE-NOTIF-002 / TC-BE-NOTIF-003 ──
    # The HTTP surface exposes no documented way to make a provider fail a chosen number of times,
    # so neither "fails twice then succeeds" (TC-002) nor "fails 6 times" (TC-003) can be arranged
    # as written. What can be observed is the terminal FAILED branch: the EMAIL provider reports a
    # failure when no destination address is supplied, and `variables` is an optional field, so
    # this is a legal documented request. Recorded, never asserted.
    def failed_branch():
        r = c.post("/api/v1/notifications/dispatch",
                   dict(base, channelHint=[CHANNEL_TYPE_EMAIL]))
        ids = (data_of(r) or {}).get("logIds") or []
        created["NotificationLog"].extend(ids)
        if not ids:
            return True, f"HTTP {r.status_code}/{err_code(r)}, no logIds", snippet(r)
        g = c.get(f"/api/v1/notifications/logs/{ids[0]}")
        return True, (f"EMAIL dispatch with no destination address -> log {ids[0]} "
                      f"notificationStatusId={field_of(g, 'notificationStatusId')}, "
                      f"retryCount={field_of(g, 'retryCount')}, "
                      f"errorMessage={field_of(g, 'errorMessage')!r}"), snippet(g, 250)

    run_observation("stage E — terminal FAILED branch (TC-BE-NOTIF-003 is not arrangeable as written)",
                    failed_branch)

    def inactive_recipient():
        """TC-BE-NOTIF-010 — RULE-NOTIF-007. Recorded, not asserted: the recipient-active check
        is XM-NOTIF-001 DEFERRED (DefaultRecipientStatusReader returns true for every id), so the
        skip cannot happen yet and asserting it would report a known deferral as a defect."""
        bad = ctx.get("inactive_recipient_id")
        if not bad:
            return True, "no inactive SEC user available to try", ""
        r = c.post("/api/v1/notifications/dispatch",
                   dict(base, recipientId=bad, channelHint=[CHANNEL_TYPE_ENABLED]))
        ids = (data_of(r) or {}).get("logIds") or []
        created["NotificationLog"].extend(ids)
        return True, (f"dispatch to inactive SEC user {bad} -> HTTP {r.status_code}, "
                      f"logIds={ids} (RULE-NOTIF-007 expects none; XM-NOTIF-001 is DEFERRED)"), snippet(r)

    run_observation("stage E — dispatch to an inactive recipient (TC-BE-NOTIF-010, XM-NOTIF-001 DEFERRED)",
                    inactive_recipient)

    def unconfigured_channel():
        other = next((x for x in (ctx.get("channel_codes") or [])
                      if x not in (CHANNEL_TYPE_EMAIL, CHANNEL_TYPE_ENABLED)), None)
        if not other:
            return True, "no other LOV-NOTIF-001 value available to try", ""
        r = c.post("/api/v1/notifications/dispatch",
                   dict(base, channelHint=[other]))
        ids = (data_of(r) or {}).get("logIds") or []
        created["NotificationLog"].extend(ids)
        if not ids:
            return True, f"HTTP {r.status_code}/{err_code(r)}, no logIds", snippet(r)
        g = c.get(f"/api/v1/notifications/logs/{ids[0]}")
        return True, (f"{other}: a valid NOTIF_CHANNEL value with no channel config row of its own -> "
                      f"notificationStatusId={field_of(g, 'notificationStatusId')}"), snippet(g, 200)

    run_observation("stage E — dispatch over a lookup-valid but unconfigured channel",
                    unconfigured_channel)

    def unknown_channel_hint():
        r = c.post("/api/v1/notifications/dispatch",
                   dict(base, channelHint=[f"NOPE{RUN_ID}"]))
        ids = (data_of(r) or {}).get("logIds") or []
        created["NotificationLog"].extend(ids)
        return True, (f"channelHint value outside the NOTIF_CHANNEL lookup -> "
                      f"HTTP {r.status_code}/{err_code(r)}, logIds={ids}"), snippet(r)

    run_observation("stage E — channelHint value that is not an LOV-NOTIF-001 code",
                    unknown_channel_hint)

    def empty_channel_hint():
        r = c.post("/api/v1/notifications/dispatch", dict(base, channelHint=[]))
        ids = (data_of(r) or {}).get("logIds") or []
        created["NotificationLog"].extend(ids)
        return True, (f"required channelHint sent empty -> HTTP {r.status_code}/{err_code(r)}, "
                      f"logIds={ids}"), snippet(r)

    run_observation("stage E — required channelHint present but empty", empty_channel_hint)

    def missing_recipient():
        payload = dict(base, channelHint=[CHANNEL_TYPE_ENABLED])
        payload.pop("recipientId")
        r = c.post("/api/v1/notifications/dispatch", payload)
        ids = (data_of(r) or {}).get("logIds") or []
        created["NotificationLog"].extend(ids)
        return True, f"required recipientId omitted -> HTTP {r.status_code}/{err_code(r)}", snippet(r)

    run_observation("stage E — required recipientId omitted", missing_recipient)


# ══════════════════════════════════════════════════════════════════
# 4. NotificationLog queries  (read-only screen — API-NOTIF-002 / 003)
# ══════════════════════════════════════════════════════════════════


def test_logs(c: APIClient):
    """Covers: API-NOTIF-002 (search), API-NOTIF-003 (get by id)
    Negative: (PLATFORM) / NOTIF_LOG_NOT_FOUND / TC-BE-NOTIF-013
    Also: TC-BE-NOTIF-012 (happy + empty page)."""
    start_suite("NotificationLog")

    def search_own():
        """Run-scoped: filters on this run's own referenceType, never a global count."""
        r = c.post("/api/v1/notifications/logs/search",
                   {"filters": [{"field": "referenceType", "operator": "EQUALS",
                                 "value": REFERENCE_TYPE}],
                    "sortField": "createdAt", "sortDirection": "DESC", "page": 0, "size": 200})
        d = data_of(r) or {}
        content = d.get("content") or []
        mine = {x.get("id") for x in content}
        expected = {i for i in created["NotificationLog"] if i}
        missing = expected - mine
        return (r.status_code == 200 and not missing,
                f"HTTP {r.status_code}, totalElements={d.get('totalElements')} for this run's "
                f"referenceType; {len(expected)} log(s) created, missing from search={missing or 'none'}",
                snippet(r, 200))

    run("TC-BE-NOTIF-012 — log search returns every log this run created", search_own)

    def paging_envelope():
        r = c.post("/api/v1/notifications/logs/search",
                   {"filters": [{"field": "referenceType", "operator": "EQUALS",
                                 "value": REFERENCE_TYPE}], "page": 0, "size": 20})
        d = data_of(r) or {}
        documented = ["totalPages", "totalElements", "numberOfElements", "first", "last",
                      "pageable", "sort", "size", "number", "empty", "content"]
        missing = [f for f in documented if f not in d]
        return (r.status_code == 200 and not missing,
                f"paging envelope fields missing={missing or 'none'} "
                f"(documented in api-docs/index.md 'Pagination Envelope')", snippet(r, 200))

    run("TC-BE-NOTIF-012 — the paging envelope carries every documented field", paging_envelope)

    def empty_page():
        """MANDATORY-J-7 — a filter matching nothing is a 200 empty page, never a 404."""
        r = c.post("/api/v1/notifications/logs/search",
                   {"filters": [{"field": "referenceType", "operator": "EQUALS",
                                 "value": f"NO_SUCH_REFERENCE_{RUN_ID}"}], "page": 0, "size": 20})
        d = data_of(r) or {}
        return (r.status_code == 200 and d.get("content") == [] and d.get("empty") is True,
                f"HTTP {r.status_code}, content={d.get('content')}, empty={d.get('empty')} "
                f"(want 200 / [] / true)", snippet(r, 200))

    run("TC-BE-NOTIF-012 — a filter matching nothing returns a 200 empty page", empty_page)

    def get_by_id():
        """TC-BE-NOTIF-013 — the response carries errorMessage and retryCount."""
        lid = next((i for i in created["NotificationLog"] if i), None)
        if not lid:
            return False, "BLOCKED: this run created no log", ""
        r = c.get(f"/api/v1/notifications/logs/{lid}")
        d = data_of(r) or {}
        required = ["id", "recipientId", "channelTypeId", "notificationStatusId", "moduleCode",
                    "retryCount", "errorMessage", "templateId"]
        missing = [f for f in required if f not in d]
        return (r.status_code == 200 and not missing,
                f"HTTP {r.status_code} for log {lid}; documented fields missing={missing or 'none'}",
                snippet(r, 250))

    run("TC-BE-NOTIF-013 — get log by id returns the documented shape (incl. retryCount, errorMessage)",
        get_by_id)

    run("TC-BE-NOTIF-013 — unknown log id -> 404 NOTIF_LOG_NOT_FOUND",
        lambda: expect_error(c.get("/api/v1/notifications/logs/99999999"),
                             404, "NOTIF_LOG_NOT_FOUND", "getById unknown"))

    # ── Stage E observations ──
    def sqli_filter_value():
        r = c.post("/api/v1/notifications/logs/search",
                   {"filters": [{"field": "moduleCode", "operator": "EQUALS",
                                 "value": SQLI_MODULE_CODE}], "page": 0, "size": 20})
        d = data_of(r) or {}
        return True, (f"SQLi string as a filter value -> HTTP {r.status_code}, "
                      f"totalElements={d.get('totalElements')} (parameterised, not executed)"), snippet(r, 150)

    run_observation("stage E — SQLi payload used as a log-search filter value", sqli_filter_value)

    def undocumented_filter_field():
        r = c.post("/api/v1/notifications/logs/search",
                   {"filters": [{"field": "errorMessage", "operator": "LIKE", "value": "x"}],
                    "page": 0, "size": 5})
        d = data_of(r) or {}
        return True, (f"a response field that is not in the filter whitelist -> "
                      f"HTTP {r.status_code}/{err_code(r)}, totalElements={d.get('totalElements')}"), snippet(r, 150)

    run_observation("stage E — filtering on an undocumented (non-whitelisted) field",
                    undocumented_filter_field)


# ══════════════════════════════════════════════════════════════════
# 5. Lookups  (API-NOTIF-006)
# ══════════════════════════════════════════════════════════════════


def test_lookups(c: APIClient):
    """Covers: API-NOTIF-006
    Negative: (PLATFORM) / NOTIF_LOOKUP_KEY_UNKNOWN / TC-BE-NOTIF-013 (ERR-0004 shape)
    Also: TC-BE-NOTIF-016 (lookups happy + SQLi)."""
    start_suite("Lookups")

    def channel_lookup():
        r = c.get(f"/api/v1/notifications/lookups/{LOOKUP_CHANNEL}")
        vals = data_of(r) or []
        shaped = all(set(v) >= {"code", "labelAr", "labelEn"} for v in vals) if vals else False
        return (r.status_code == 200 and shaped,
                f"HTTP {r.status_code}, {len(vals)} option(s), every option carries "
                f"code/labelAr/labelEn = {shaped}", snippet(r, 200))

    run(f"TC-BE-NOTIF-016 — GET lookups/{LOOKUP_CHANNEL} returns bilingual options", channel_lookup)

    def status_lookup():
        r = c.get(f"/api/v1/notifications/lookups/{LOOKUP_STATUS}")
        vals = data_of(r) or []
        return (r.status_code == 200 and len(vals) > 0,
                f"HTTP {r.status_code}, {len(vals)} option(s)", snippet(r, 200))

    run(f"TC-BE-NOTIF-016 — GET lookups/{LOOKUP_STATUS} returns bilingual options", status_lookup)

    run("TC-BE-NOTIF-013 — unknown lookupKey -> 404 NOTIF_LOOKUP_KEY_UNKNOWN",
        lambda: expect_error(c.get(f"/api/v1/notifications/lookups/NO_SUCH_KEY_{RUN_ID}"),
                             404, "NOTIF_LOOKUP_KEY_UNKNOWN", "unknown lookupKey"))

    def sqli_lookup_key():
        r = c.get("/api/v1/notifications/lookups/" + requests.utils.quote(SQLI_MODULE_CODE, safe=""))
        after = c.get(f"/api/v1/notifications/lookups/{LOOKUP_CHANNEL}")
        intact = after.status_code == 200 and len(data_of(after) or []) == len(ctx.get("channel_codes") or [])
        return (r.status_code == 404 and intact,
                f"SQLi as the lookupKey -> HTTP {r.status_code}/{err_code(r)} "
                f"(want 404, the module rejects keys it does not own); DB intact={intact}",
                snippet(r, 200))

    run("TC-BE-NOTIF-016 — SQLi as lookupKey is rejected and the lookup data stays intact",
        sqli_lookup_key)


# ══════════════════════════════════════════════════════════════════
# 6. Authorization  (RULE-NOTIF-005 — delegated to the Security filter)
# ══════════════════════════════════════════════════════════════════


def test_authorization(c: APIClient):
    """Covers: TC-BE-NOTIF-007 (no/invalid JWT -> 401 from the Security filter),
    and the permission half of TC-BE-NOTIF-014."""
    start_suite("Authorization (RULE-NOTIF-005)")

    run("TC-BE-NOTIF-007 — log search with no JWT -> 401",
        lambda: expect_status(
            c.post("/api/v1/notifications/logs/search", {"page": 0, "size": 5}, anonymous=True),
            401, "anonymous log search"))

    run("TC-BE-NOTIF-007 — log search with an invalid JWT -> 401",
        lambda: expect_status(
            c.post("/api/v1/notifications/logs/search", {"page": 0, "size": 5},
                   token="not.a.valid.token"),
            401, "invalid-JWT log search"))

    run("TC-BE-NOTIF-007 — dispatch with no JWT -> 401",
        lambda: expect_status(
            c.post("/api/v1/notifications/dispatch", {}, anonymous=True), 401, "anonymous dispatch"))

    run("TC-BE-NOTIF-007 — lookups with no JWT -> 401",
        lambda: expect_status(
            c.get(f"/api/v1/notifications/lookups/{LOOKUP_CHANNEL}", anonymous=True),
            401, "anonymous lookup"))

    run("TC-BE-NOTIF-007 — templates with no JWT -> 401",
        lambda: expect_status(
            c.get("/api/v1/notifications/templates/1", anonymous=True), 401, "anonymous template read"))


# ══════════════════════════════════════════════════════════════════
# Stage F — teardown
# ══════════════════════════════════════════════════════════════════


def cleanup(c: APIClient):
    """Reverse of the manifest's DEPENDENCY ORDER (log -> channel -> template).
    NOTIF documents NO hard-delete endpoint for any entity, so every call below is the
    documented soft deactivate/disable and the rows survive — listed individually in the
    report, never summarised as 'cleaned up'."""
    print("\n=== CLEANUP (reverse dependency order) ===")

    log_ids = [i for i in created["NotificationLog"] if i]
    if log_ids:
        LEFT_BEHIND.append(
            f"NotificationLog: {len(log_ids)} row(s) {log_ids} — the ENTITY CRUD CHECKLIST marks "
            f"NOTIF_LOG a read-only screen with no delete and no deactivate endpoint, so they "
            f"survive. All carry referenceType='{REFERENCE_TYPE}'. "
            f"Cleanup SQL: DELETE FROM NOTIF_LOG WHERE REFERENCE_TYPE = '{REFERENCE_TYPE}';")

    for cid in [i for i in created["NotificationChannelConfig"] if i]:
        try:
            r = c.delete(f"/api/v1/notifications/channels/{cid}")
            print(f"  disable channel {cid}: {r.status_code}")
        except Exception as e:  # noqa: BLE001
            print(f"  disable channel {cid} FAILED: {e}")
    if [i for i in created["NotificationChannelConfig"] if i]:
        PERMANENT_RESIDUE.append(
            f"NOTIF_CHANNEL_CONFIG rows {[i for i in created['NotificationChannelConfig'] if i]} "
            f"(channelTypeId "
            f"{[CHANNEL_TYPE_ENABLED, ctx.get('undocumented_channel_code')]}) — disabled via the "
            f"documented DELETE, but the rows persist and CHANNEL_TYPE_ID is UNIQUE, so a later "
            f"run creating the same channel type gets 409. This table is read by dispatch for "
            f"every module that sends a notification. "
            f"Cleanup SQL: DELETE FROM NOTIF_CHANNEL_CONFIG WHERE CHANNEL_TYPE_ID IN "
            f"('{CHANNEL_TYPE_ENABLED}', '{ctx.get('undocumented_channel_code')}');")

    for tid in [i for i in created["NotificationTemplate"] if i]:
        try:
            r = c.delete(f"/api/v1/notifications/templates/{tid}")
            print(f"  deactivate template {tid}: {r.status_code}")
        except Exception as e:  # noqa: BLE001
            print(f"  deactivate template {tid} FAILED: {e}")
    if [i for i in created["NotificationTemplate"] if i]:
        LEFT_BEHIND.append(
            f"NotificationTemplate: {[i for i in created['NotificationTemplate'] if i]} — "
            f"deactivated (soft, isActiveFl=false); NOTIF documents no hard delete. Codes are "
            f"RUN_ID-suffixed ('%_{RUN_ID}'). "
            f"Cleanup SQL: DELETE FROM NOTIF_TEMPLATE WHERE TEMPLATE_CODE LIKE '%\\_{RUN_ID}';")


# ══════════════════════════════════════════════════════════════════
# Report
# ══════════════════════════════════════════════════════════════════


def write_report(path: str):
    total_p = sum(s.passed_count for s in SUITES)
    total_f = sum(s.failed_count for s in SUITES)
    lines = [
        "# NOTIF — api-verify problems report",
        "",
        f"Generated: {date.today().isoformat()} · RUN_ID `{RUN_ID}` · tier **Full** "
        f"(api-docs + P3_5_BE/test-execution-manifest.md present)",
        f"Target: `{BASE_URL}` (Dev/Test — localhost, per api-verify-config.md §4.1)",
        "",
        f"**{total_p} passed · {total_f} failed** across {len(SUITES)} suites · "
        f"{len(OBSERVATIONS)} observation(s), which never affect the totals.",
        "",
        "## Suites",
        "",
        "| Suite | Passed | Failed |",
        "|---|---|---|",
    ]
    for s in SUITES:
        lines.append(f"| {s.entity} | {s.passed_count} | {s.failed_count} |")

    lines += ["", "## Failures", ""]
    fails = [(s, r) for s in SUITES for r in s.results if not r.passed]
    if not fails:
        lines.append("_None._")
    else:
        lines.append("| Suite | Test | Detail | Response |")
        lines.append("|---|---|---|---|")
        for s, r in fails:
            det = r.detail.replace("|", "\\|")[:300]
            snip = (r.response_snippet or "").replace("|", "\\|")[:200]
            lines.append(f"| {s.entity} | {r.name} | {det} | `{snip}` |")

    lines += [
        "", "## Failure classification (stage G)", "",
        "### Likely real bug", "",
        "_None._ Every asserted rejection that the manifest promises did happen, with the "
        "promised HTTP status.",
        "",
        "### Test assumption / governance-document mismatch", "",
        "- **RULE-NOTIF-004 / ERR-0001 (`NOTIF_TEMPLATE_BILINGUAL_REQUIRED`) is not reachable "
        "through the HTTP surface.** `TemplateCreateRequest.bodyAr/bodyEn` and "
        "`TemplateUpdateRequest.bodyAr/bodyEn` carry `@NotBlank`, so bean validation rejects the "
        "request before `NotificationTemplateDomain.create()` / `assertBilingualBody()` can throw "
        "the module's own code. The caller gets the manifest's HTTP 400, but with the platform "
        "code `VALIDATION_ERROR` and `fieldErrors[{field: bodyEn}]`, never "
        "`NOTIF_TEMPLATE_BILINGUAL_REQUIRED`. TC-BE-NOTIF-006 asserts the manifest triple "
        "verbatim and therefore fails on the code. The expectation (or the DTO annotation), not "
        "the service, is what is out of step — this was deliberately left failing rather than "
        "weakened, because the module advertises a code in its api-docs 'Known Error Codes' "
        "table that no request can actually produce.",
        "",
        "### Infrastructure", "",
        "_None._",
        "",
        "## Governed-case coverage (backend-test-plan.md, TC-BE-NOTIF-001..016)", "",
        "| TC | Covered by | Result |",
        "|---|---|---|",
        "| TC-BE-NOTIF-001 fan-out one log per channel | `test_dispatch` | covered |",
        "| TC-BE-NOTIF-002 retry then success | — | **GAP** — the HTTP surface offers no "
        "documented way to make the provider fail a chosen number of times and then succeed; "
        "no fault-injection endpoint, header or config field exists. Not simulated. |",
        "| TC-BE-NOTIF-003 exhausted retries -> FAILED | `test_dispatch` (observation only) | "
        "**GAP (partial)** — the terminal FAILED branch is observed (EMAIL dispatch with no "
        "destination address: status FAILED, retryCount 4, errorMessage recorded), but the "
        "'provider fails 6 times' precondition cannot be arranged from HTTP, and the failure "
        "mode used is read out of the provider implementation, not out of a governed document. "
        "Recorded as an observation, never asserted. |",
        "| TC-BE-NOTIF-004 disabled channel -> CHANNEL_DISABLED | `test_dispatch` | covered |",
        "| TC-BE-NOTIF-005 bilingual template accepted | `test_template` | covered |",
        "| TC-BE-NOTIF-006 missing bilingual body rejected | `test_template` | covered — "
        "**failing on the error code**, see the classification above |",
        "| TC-BE-NOTIF-007 auth delegated to the Security filter | `test_authorization` | covered |",
        "| TC-BE-NOTIF-008 unique codes accepted | `test_template`, `test_channel` | covered |",
        "| TC-BE-NOTIF-009 duplicate code rejected (template + channel) | `test_template`, "
        "`test_channel` | covered |",
        "| TC-BE-NOTIF-010 skip inactive recipient | `test_dispatch` (observation only) | "
        "**GAP** — `DefaultRecipientStatusReader` is the XM-NOTIF-001 DEFERRED stub and returns "
        "true for every id, so no recipient can be inactive from NOTIF's point of view. "
        "Observed (a dispatch to an inactive SEC user still creates a log) and left as an "
        "observation: asserting it would report a documented deferral as a defect. |",
        "| TC-BE-NOTIF-011 dispatch happy -> {logIds} | `test_dispatch` | covered — "
        "**status is 200, not the plan's 202** (see the note below) |",
        "| TC-BE-NOTIF-012 query logs happy + empty page | `test_logs` | covered |",
        "| TC-BE-NOTIF-013 log by id + unknown id 404 | `test_logs` (plus the same ERR-0004 "
        "shape on template, channel and lookup) | covered |",
        "| TC-BE-NOTIF-014 templates CRUD + permission | `test_template`, `test_authorization` | "
        "covered for CRUD; the **permission half is a GAP** — every NOTIF service's "
        "`@PreAuthorize(hasAuthority(PERM_NOTIF_*))` is commented out as SEC-PENDING, so there "
        "is no page permission to withhold and no 403 to provoke. Only the platform 401 is "
        "verifiable today. |",
        "| TC-BE-NOTIF-015 channels CRUD/enable + toggle affects dispatch | `test_channel`, "
        "`test_dispatch` | covered |",
        "| TC-BE-NOTIF-016 lookups happy + SQLi | `test_lookups`, `test_dispatch` | covered |",
        "",
        "## Convention divergences from api-verify-config.md §3", "",
        "- **Error-code format.** The config states `{MOD}-{http}[-{SLUG}]` (SEC emits "
        "`SEC-401-INVALID-CREDENTIALS`). NOTIF emits descriptive `SCREAMING_SNAKE` codes with no "
        "module/status prefix — `NOTIF_TEMPLATE_NOT_FOUND`, `NOTIF_LOOKUP_KEY_UNKNOWN`. The "
        "module's own api-docs document the snake form, so every assertion here uses it; the "
        "divergence itself is the finding.",
        "- **Error envelope.** The config states `{code, messageAr, messageEn}`. The live "
        "envelope is `{code, message, fieldErrors}` — one already-negotiated message, not a "
        "bilingual pair — so no bilingual-message assertion was possible and none was invented.",
        "- **Dispatch status code.** `backend-test-plan.md` TC-BE-NOTIF-011 and the manifest say "
        "202. The service returns 200, and `DispatchService` records the divergence as a known "
        "`api_doc_gap` (the shared `Status` taxonomy has no 202). The api-docs are authoritative "
        "per api-verify-config.md §1, so 200 is what is asserted.",
        "",
        "## Preconditions (stage A0)", ""]
    lines += ([f"- {p}" for p in PRECONDITION_FAILURES] or ["_All preconditions satisfied._"])

    lines += ["", "## Observations (stage E — not pass/fail)", ""]
    lines += ([f"- **{o.name}** — {o.detail}" for o in OBSERVATIONS] or ["_None._"])

    lines += ["", "## Surviving records", ""]
    lines += ([f"- {n}" for n in LEFT_BEHIND] or ["_None._"])

    lines += ["", "### Permanent residue (reference tables other modules' behaviour reads)", ""]
    lines += ([f"- {n}" for n in PERMANENT_RESIDUE] or ["_None._"])

    lines += [
        "", "## Privileges",
        "",
        "No permission grant was created or revoked by this run, and no grant journal was "
        "written. Every NOTIF service method's authority check is currently commented out "
        "(`// TODO: SEC-PENDING — re-add @PreAuthorize(hasAuthority(PermissionConstants.PERM_NOTIF_*))`), "
        "so no NOTIF endpoint is gated by a PERM_NOTIF_* permission and there was nothing for "
        "stage I to grant. No standing privilege was left behind.",
        "",
    ]
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"\nReport written: {path}")


# ══════════════════════════════════════════════════════════════════
# main
# ══════════════════════════════════════════════════════════════════


def main() -> int:
    global BASE_URL
    if len(sys.argv) > 1:
        BASE_URL = sys.argv[1].rstrip("/")

    c = APIClient(BASE_URL)
    print(f"api-verify — NOTIF · tier Full · RUN_ID={RUN_ID} · target {BASE_URL}")

    tok = c.login(ADMIN_USERNAME, ADMIN_PASSWORD)
    if not tok:
        print("FATAL: could not authenticate — ENVIRONMENT_FAILURE", file=sys.stderr)
        return 2
    c.token = tok

    try:
        grants(c)
        preflight(c)
        test_template(c)      # DEPENDENCY ORDER 1
        test_channel(c)       # DEPENDENCY ORDER 2
        test_dispatch(c)      # DEPENDENCY ORDER 3 (creates NOTIF_LOG via fan-out)
        test_logs(c)
        test_lookups(c)
        test_authorization(c)
    finally:
        try:
            cleanup(c)
        except Exception as e:  # noqa: BLE001
            print(f"cleanup FAILED: {e}")
        write_report(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                  "notif_problems_report.md"))

    total_f = sum(s.failed_count for s in SUITES)
    print(f"\nTOTAL: {sum(s.passed_count for s in SUITES)} passed, {total_f} failed")
    return 1 if total_f else 0


if __name__ == "__main__":
    raise SystemExit(main())
